# Generated by Django 5.2.15 on 2026-08-17 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_approvaldelegation_projectstaffassignment'),
        ('suppliers', '0002_supplier_compliance_expiry_date_and_more'),
        ('warehouse', '0011_stockmovement_work_order'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='projects.project'),
        ),
        migrations.CreateModel(
            name='WorkOrderSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('estimated_start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_work_orders', to='suppliers.supplier')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_site_packages', to='projects.project')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_work_orders', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_order_site_packages', to='warehouse.warehouse')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_packages', to='workorders.workorder')),
            ],
            options={
                'ordering': ['project__name', 'site__name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='workordertask',
            name='site_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workorders.workordersite'),
        ),
        migrations.AddConstraint(
            model_name='workordersite',
            constraint=models.UniqueConstraint(fields=('work_order', 'project', 'site'), name='unique_site_package_per_work_order'),
        ),
    ]
