# Generated by Django 5.2.15 on 2026-08-17 13:00

from django.conf import settings
from django.db import migrations, models


def connect_existing_site_packages(apps, schema_editor):
    WorkOrder = apps.get_model('workorders', 'WorkOrder')
    WorkOrderSite = apps.get_model('workorders', 'WorkOrderSite')
    Warehouse = apps.get_model('warehouse', 'Warehouse')
    ProjectSite = apps.get_model('projects', 'ProjectSite')
    for package in WorkOrderSite.objects.filter(project_site__isnull=True).select_related('site', 'project'):
        physical_site_id = getattr(package.site, 'project_site_id', None) if package.site_id else None
        if not physical_site_id:
            code = f'WO-{package.pk}'
            physical_site, _ = ProjectSite.objects.get_or_create(
                project_id=package.project_id, code=code,
                defaults={'name': package.title or f'Work order site {package.pk}'},
            )
            physical_site_id = physical_site.pk
        WorkOrderSite.objects.filter(pk=package.pk).update(project_site_id=physical_site_id)
    for work_order in WorkOrder.objects.filter(project__isnull=True):
        package = WorkOrderSite.objects.filter(work_order_id=work_order.pk).order_by('id').first()
        if package:
            WorkOrder.objects.filter(pk=work_order.pk).update(project_id=package.project_id)
    # Historical data allowed more than one package against a store. Preserve
    # every package and make each accountable physical location explicit
    # before the new uniqueness control is added.
    seen = set()
    for package in WorkOrderSite.objects.order_by('work_order_id', 'project_site_id', 'id'):
        key = (package.work_order_id, package.project_site_id)
        if key not in seen:
            seen.add(key)
            continue
        original = ProjectSite.objects.get(pk=package.project_site_id)
        physical_site = ProjectSite.objects.create(
            project_id=package.project_id,
            code=f'WO-{package.pk}',
            name=f'{original.name} — {package.title or "work package"}',
            location=original.location,
            description='Created during work-order site-package integrity migration.',
        )
        WorkOrderSite.objects.filter(pk=package.pk).update(project_site_id=physical_site.pk)


def reverse_connect_existing_site_packages(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectsite'),
        ('suppliers', '0003_supplier_contractor_specialty_supplier_is_contractor'),
        ('warehouse', '0013_warehouse_project_site'),
        ('workorders', '0003_workordersite_project_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workordersite',
            name='unique_site_package_per_work_order',
        ),
        migrations.RunPython(connect_existing_site_packages, reverse_connect_existing_site_packages),
        migrations.AddConstraint(
            model_name='workordersite',
            constraint=models.UniqueConstraint(fields=('work_order', 'project_site'), name='unique_physical_site_package_per_work_order'),
        ),
    ]
