# Generated by Django 5.2.15 on 2026-08-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_remove_workordersite_unique_site_package_per_work_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='progress_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='progress_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
