# Generated by Django 5.2.15 on 2026-08-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_workorder_progress_notes_workorder_progress_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='progress_notes',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='progress_percent',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='progress_updated_at',
        ),
        migrations.AddField(
            model_name='workordersite',
            name='progress_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workordersite',
            name='progress_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workordersite',
            name='progress_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
