# Generated by Django 5.2.15 on 2026-08-21 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_contractor_specialty_supplier_is_contractor'),
        ('workorders', '0006_remove_workorder_progress_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='approved_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='workorder',
            name='assignment_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='assignment_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='assignment_status',
            field=models.CharField(choices=[('PENDING', 'Awaiting acceptance'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=12),
        ),
        migrations.AddField(
            model_name='workorder',
            name='emergency_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='emergency_spend_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='workorder',
            name='finance_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='finance_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='finance_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_reviewed_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='hold_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_work_order_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='hold_recovery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='revised_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='scope_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='workordersite',
            name='client_signed_off',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workordersite',
            name='closeout_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workordersite',
            name='hold_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_site_work_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workordersite',
            name='hold_recovery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordersite',
            name='materials_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workordersite',
            name='quality_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workordersite',
            name='revised_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordersite',
            name='safety_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workordertask',
            name='blocker',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workordertask',
            name='completion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workordertask',
            name='dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_tasks', to='workorders.workordertask'),
        ),
        migrations.AddField(
            model_name='workordertask',
            name='planned_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='workordertask',
            name='planned_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workordertask',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10),
        ),
        migrations.CreateModel(
            name='WorkOrderChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('proposed_scope', models.TextField(blank=True)),
                ('proposed_due_date', models.DateField(blank=True, null=True)),
                ('proposed_estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=12)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_work_order_changes', to='suppliers.supplier')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_work_order_changes', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_work_order_changes', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='workorders.workorder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
