# Generated by Django 4.2.30 on 2026-07-26 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_chat_rooms_for_existing_projects(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    ChatRoom = apps.get_model('projects', 'ChatRoom')
    rooms = [
        ChatRoom(company_id=project.company_id, project_id=project.id)
        for project in Project.objects.all()
        if not ChatRoom.objects.filter(project_id=project.id).exists()
    ]
    ChatRoom.objects.bulk_create(rooms)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_chat_rooms', to='accounts.company')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='projects.project')),
            ],
            options={
                'ordering': ['project__name'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_system_message', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projects.chatroom')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(create_chat_rooms_for_existing_projects, migrations.RunPython.noop),
    ]
