# Generated by Django 5.2.15 on 2026-08-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('site_engineer', 'Site Engineer'), ('storekeeper', 'Storekeeper'), ('project_manager', 'Project Manager'), ('procurement_officer', 'Procurement Officer'), ('finance_officer', 'Finance Officer'), ('finance_manager', 'Finance Manager'), ('finance_viewer', 'Finance Viewer'), ('admin', 'Admin')], default='site_engineer', max_length=32),
        ),
    ]
