# Generated by Django 5.2.15 on 2026-08-14 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='active_session_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
