# Generated by Codex on 2026-07-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='priority',
            field=models.CharField(
                choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')],
                default='NORMAL',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Pending'),
                    ('APPROVED', 'Approved'),
                    ('REJECTED', 'Rejected'),
                    ('PO_CREATED', 'PO Created'),
                ],
                default='PENDING',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='PurchaseRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_request_items', to='materials.material')),
                ('purchase_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procurement.purchaserequest')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
