# Generated by Django 5.2.15 on 2026-07-29 13:20

import django.db.models.deletion
from django.db import migrations, models


def link_existing_suppliers(apps, schema_editor):
    PurchaseOrder = apps.get_model('procurement', 'PurchaseOrder')
    Supplier = apps.get_model('suppliers', 'Supplier')
    for purchase_order in PurchaseOrder.objects.filter(supplier__isnull=True).exclude(supplier_name=''):
        supplier = Supplier.objects.filter(
            company_id=purchase_order.company_id,
            name__iexact=purchase_order.supplier_name.strip(),
        ).first()
        if supplier:
            purchase_order.supplier_id = supplier.id
            purchase_order.save(update_fields=['supplier'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('materials', '0001_initial'),
        ('procurement', '0007_purchase_order_dispatch_confirmation'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PR', 'Purchase Request'), ('PO', 'Purchase Order')], max_length=10)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier'),
        ),
        migrations.RunPython(link_existing_suppliers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'material'), name='unique_material_per_purchase_order'),
        ),
        migrations.AddConstraint(
            model_name='purchaserequestitem',
            constraint=models.UniqueConstraint(fields=('purchase_request', 'material'), name='unique_material_per_purchase_request'),
        ),
        migrations.AddField(
            model_name='documentsequence',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='accounts.company'),
        ),
        migrations.AddConstraint(
            model_name='documentsequence',
            constraint=models.UniqueConstraint(fields=('company', 'document_type'), name='unique_company_document_sequence'),
        ),
    ]
