# Generated by Django 5.2.15 on 2026-08-01 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('procurement', '0008_documentsequence_purchaseorder_supplier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsequence',
            name='document_type',
            field=models.CharField(choices=[('PR', 'Purchase Request'), ('PO', 'Purchase Order'), ('GRN', 'Goods Received Note')], max_length=10),
        ),
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('receipt_date', models.DateField()),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REVERSED', 'Reversed')], default='ACCEPTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='accounts.company')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='procurement.purchaseorder')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rejected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('damaged_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_note_items', to='accounts.company')),
                ('goods_received_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='procurement.goodsreceivednote')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_note_items', to='procurement.purchaseorderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='goodsreceivednote',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_company_grn_number'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceivednoteitem',
            constraint=models.UniqueConstraint(fields=('goods_received_note', 'purchase_order_item'), name='unique_po_item_per_grn'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceivednoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_quantity__gte', 0)), name='grn_accepted_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceivednoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('rejected_quantity__gte', 0)), name='grn_rejected_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceivednoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('damaged_quantity__gte', 0)), name='grn_damaged_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceivednoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('accepted_quantity__gt', 0), ('rejected_quantity__gt', 0), ('damaged_quantity__gt', 0), _connector='OR'), name='grn_item_has_quantity'),
        ),
    ]
