# Generated by Django 5.2.15 on 2026-08-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_user_active_session_id_and_more'),
        ('procurement', '0011_purchase_request_technical_return'),
        ('projects', '0004_project_site_engineers'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('AWAITING_SUPPLIER', 'Awaiting supplier'), ('RETURN_PENDING', 'Return pending'), ('REPLACEMENT_PENDING', 'Replacement pending'), ('CREDIT_PENDING', 'Credit note pending'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('supplier_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_supplier_claims', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_claims', to='accounts.company')),
                ('goods_received_note_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_claim', to='procurement.goodsreceivednoteitem')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_claims', to='projects.project')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_claims', to='procurement.purchaseorder')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_supplier_claims', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_supplier_claims', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
                'indexes': [
                    models.Index(fields=['company', 'status'], name='supclaim_co_status_idx'),
                    models.Index(fields=['company', 'due_date'], name='supplier_claim_company_due_idx'),
                ],
            },
        ),
    ]
