# Generated by Django 5.2.15 on 2026-08-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('procurement', '0012_supplierclaim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(model_name='purchaseorder', name='expected_delivery_date', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='purchaseorder', name='supplier_confirmed_delivery_date', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='purchaseorder', name='revised_delivery_date', field=models.DateField(blank=True, null=True)),
        migrations.AddField(model_name='purchaseorder', name='delivery_revision_reason', field=models.TextField(blank=True)),
        migrations.AddField(model_name='purchaseorder', name='delivery_follow_up_owner', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_follow_up_purchase_orders', to=settings.AUTH_USER_MODEL)),
    ]
