# Generated by Django 5.2.15 on 2026-08-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_alter_supplierclaim_status'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='workorders.workorder'),
        ),
    ]
