# Generated by Django 5.2.15 on 2026-08-25 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_manager_approvals(apps, schema_editor):
    PurchaseRequest = apps.get_model('procurement', 'PurchaseRequest')
    User = apps.get_model('accounts', 'User')
    manager_ids = User.objects.filter(role='project_manager').values_list('id', flat=True)
    PurchaseRequest.objects.filter(
        technical_approved_by_id__in=manager_ids,
        manager_approved_by__isnull=True,
    ).update(manager_approved_by_id=models.F('technical_approved_by_id'))


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0022_purchaserequest_technical_approved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_approved_purchase_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_manager_approvals, migrations.RunPython.noop),
    ]
