# Generated by Django 5.2.15 on 2026-09-18 06:12

from django.db import migrations, models


def rename_purchase_request_numbers(apps, schema_editor):
    PurchaseRequest = apps.get_model('procurement', 'PurchaseRequest')
    for request in PurchaseRequest.objects.filter(number__startswith='PR-').iterator():
        new_number = f"MR-{request.number[3:]}"
        if not PurchaseRequest.objects.filter(company_id=request.company_id, number=new_number).exclude(pk=request.pk).exists():
            PurchaseRequest.objects.filter(pk=request.pk).update(number=new_number)


def restore_purchase_request_numbers(apps, schema_editor):
    PurchaseRequest = apps.get_model('procurement', 'PurchaseRequest')
    for request in PurchaseRequest.objects.filter(number__startswith='MR-').iterator():
        old_number = f"PR-{request.number[3:]}"
        if not PurchaseRequest.objects.filter(company_id=request.company_id, number=old_number).exclude(pk=request.pk).exists():
            PurchaseRequest.objects.filter(pk=request.pk).update(number=old_number)


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0024_purchaserequest_delivery_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsequence',
            name='document_type',
            field=models.CharField(choices=[('PR', 'Material Request'), ('PO', 'Purchase Order'), ('GRN', 'Goods Received Note')], max_length=10),
        ),
        migrations.RunPython(rename_purchase_request_numbers, restore_purchase_request_numbers),
    ]
