# Generated by Django 5.2.15 on 2026-08-01 08:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('materials', '0001_initial'),
        ('procurement', '0008_documentsequence_purchaseorder_supplier_and_more'),
        ('projects', '0004_project_site_engineers'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=20)),
                ('system_key', models.CharField(blank=True, choices=[('CASH', 'Cash/Bank'), ('ACCOUNTS_PAYABLE', 'Accounts Payable'), ('INVENTORY', 'Inventory'), ('PROJECT_COST', 'Project Cost')], max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_accounts', to='accounts.company')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('review_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_approvals', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_budget_approvals', to=settings.AUTH_USER_MODEL)),
                ('purchase_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='budget_approval', to='procurement.purchaserequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_budget_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceDocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('INV', 'Supplier Invoice'), ('PAY', 'Payment'), ('JE', 'Journal Entry')], max_length=10)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_sequences', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('source_type', models.CharField(choices=[('INVOICE', 'Supplier Invoice'), ('PAYMENT', 'Payment'), ('INVOICE_REVERSAL', 'Invoice Reversal'), ('PAYMENT_REVERSAL', 'Payment Reversal')], max_length=30)),
                ('source_object_id', models.PositiveBigIntegerField()),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounts.company')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entry', to='finance.journalentry')),
            ],
            options={
                'ordering': ['-date', '-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounts.company')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.journalentry')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='projects.project')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('BANK', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Cheque'), ('CASH', 'Cash')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_payments', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_finance_payments', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='finance.journalentry')),
            ],
            options={
                'ordering': ['-payment_date', '-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('is_reversal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_project_costs', to='accounts.company')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_costs', to='finance.journalentry')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_costs', to='finance.payment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_costs', to='projects.project')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_cost', to='finance.projectcost')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('idempotency_key', models.CharField(max_length=100)),
                ('reversed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_reversals', to='accounts.company')),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_reversal', to='finance.journalentry')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.payment')),
                ('reversed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversed_finance_payments', to=settings.AUTH_USER_MODEL)),
                ('project_cost', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_reversal', to='finance.projectcost')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MATCHED', 'Matched'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='projects.project')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='procurement.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectcost',
            name='supplier_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_costs', to='finance.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.supplierinvoice'),
        ),
        migrations.CreateModel(
            name='InvoiceReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('idempotency_key', models.CharField(max_length=100)),
                ('reversed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_reversals', to='accounts.company')),
                ('reversed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reversed_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_reversal', to='finance.journalentry')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.supplierinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_items', to='accounts.company')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.supplierinvoice')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_items', to='materials.material')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_items', to='procurement.purchaseorderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ThreeWayMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('EXCEPTION', 'Exception')], max_length=20)),
                ('tolerance', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('po_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('invoice_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('received_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('quantity_variance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('amount_variance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('exceptions', models.JSONField(blank=True, default=list)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('matched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='three_way_matches', to='accounts.company')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='three_way_match', to='finance.supplierinvoice')),
                ('matched_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_three_way_matches', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='three_way_matches', to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ['-matched_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_account_code'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('system_key', ''), _negated=True), fields=('company', 'system_key'), name='unique_company_system_account'),
        ),
        migrations.AddConstraint(
            model_name='budgetapproval',
            constraint=models.CheckConstraint(condition=models.Q(('requested_amount__gte', 0)), name='budget_requested_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='financedocumentsequence',
            constraint=models.UniqueConstraint(fields=('company', 'document_type'), name='unique_company_finance_sequence'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_company_journal_number'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('company', 'source_type', 'source_object_id'), name='unique_finance_source_journal'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='journal_line_single_positive_side'),
        ),
        migrations.AddConstraint(
            model_name='paymentreversal',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='unique_company_payment_reversal_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(fields=('company', 'internal_number'), name='unique_company_internal_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(fields=('company', 'supplier', 'invoice_number'), name='unique_company_supplier_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='unique_company_invoice_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='invoice_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='invoice_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='invoice_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='projectcost',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reversal', False)), fields=('payment',), name='unique_original_project_cost_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='projectcost',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='project_cost_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='projectcost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_reversal', False), ('reversal_of__isnull', True)), models.Q(('is_reversal', True), ('reversal_of__isnull', False)), _connector='OR'), name='project_cost_reversal_consistency'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_company_payment_number'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='unique_company_payment_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoicereversal',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='unique_company_invoice_reversal_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceitem',
            constraint=models.UniqueConstraint(fields=('invoice', 'purchase_order_item'), name='unique_po_item_per_supplier_invoice'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='invoice_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='invoice_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='invoice_item_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='threewaymatch',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='unique_company_match_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='threewaymatch',
            constraint=models.CheckConstraint(condition=models.Q(('tolerance__gte', 0)), name='match_tolerance_nonnegative'),
        ),
    ]
