# Generated by Django 5.2.15 on 2026-08-01 08:40

import apps.finance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def create_company_finance_defaults(apps, schema_editor):
    Company = apps.get_model('accounts', 'Company')
    Currency = apps.get_model('finance', 'Currency')
    FinanceSettings = apps.get_model('finance', 'FinanceSettings')
    today = timezone.localdate()
    financial_year_start = today.replace(month=7, day=1)
    if financial_year_start > today:
        financial_year_start = financial_year_start.replace(year=today.year - 1)
    for company in Company.objects.all().iterator():
        currency, _ = Currency.objects.get_or_create(
            company=company,
            code='UGX',
            defaults={
                'name': 'Uganda Shilling',
                'symbol': 'UGX',
                'decimal_places': 0,
            },
        )
        FinanceSettings.objects.get_or_create(
            company=company,
            defaults={
                'base_currency': currency,
                'financial_year_start': financial_year_start,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('finance', '0001_initial'),
        ('projects', '0004_project_site_engineers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_cost_centres', to='accounts.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cost_centres', to='projects.project')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_budget_categories', to='accounts.company')),
                ('cost_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_categories', to='finance.costcentre')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_currencies', to='accounts.company')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FinanceAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_audit_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_audit_events', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year_start', models.DateField(default=apps.finance.models.default_financial_year_start)),
                ('quantity_matching_tolerance', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('price_matching_tolerance', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('finance_officer_approval_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('finance_manager_approval_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('maker_checker_enforced', models.BooleanField(default=True)),
                ('negative_stock_policy', models.CharField(choices=[('PREVENT', 'Prevent'), ('WARN', 'Warn'), ('ALLOW', 'Allow')], default='PREVENT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_for_settings', to='finance.currency')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='finance_settings', to='accounts.company')),
            ],
            options={
                'verbose_name_plural': 'finance settings',
            },
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('rate_percent', models.DecimalField(decimal_places=4, max_digits=7)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_tax_codes', to='accounts.company')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddConstraint(
            model_name='costcentre',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_cost_centre'),
        ),
        migrations.AddConstraint(
            model_name='budgetcategory',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_budget_category'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_currency_code'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.CheckConstraint(condition=models.Q(('decimal_places__lte', 6)), name='currency_decimal_places_max_six'),
        ),
        migrations.AddIndex(
            model_name='financeauditevent',
            index=models.Index(fields=['company', 'created_at'], name='finance_audit_company_time'),
        ),
        migrations.AddIndex(
            model_name='financeauditevent',
            index=models.Index(fields=['company', 'object_type', 'object_id'], name='finance_audit_object'),
        ),
        migrations.AddConstraint(
            model_name='financesettings',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_matching_tolerance__gte', 0)), name='finance_quantity_tolerance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='financesettings',
            constraint=models.CheckConstraint(condition=models.Q(('price_matching_tolerance__gte', 0)), name='finance_price_tolerance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='financesettings',
            constraint=models.CheckConstraint(condition=models.Q(('finance_officer_approval_threshold__gte', 0)), name='finance_officer_threshold_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='financesettings',
            constraint=models.CheckConstraint(condition=models.Q(('finance_manager_approval_threshold__gte', 0)), name='finance_manager_threshold_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='taxcode',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_tax_code'),
        ),
        migrations.AddConstraint(
            model_name='taxcode',
            constraint=models.CheckConstraint(condition=models.Q(('rate_percent__gte', 0)), name='tax_rate_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='taxcode',
            constraint=models.CheckConstraint(condition=models.Q(('rate_percent__lte', 100)), name='tax_rate_max_hundred'),
        ),
        migrations.RunPython(create_company_finance_defaults, migrations.RunPython.noop),
    ]
