# Generated by Django 5.2.15 on 2026-08-01 08:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('finance', '0002_costcentre_budgetcategory_currency_financeauditevent_and_more'),
        ('procurement', '0008_documentsequence_purchaseorder_supplier_and_more'),
        ('projects', '0004_project_site_engineers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialApproval',
            fields=[
            ],
            options={
                'verbose_name': 'financial approval',
                'verbose_name_plural': 'financial approvals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finance.budgetapproval',),
        ),
        migrations.AlterField(
            model_name='budgetapproval',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned'), ('HOLD', 'On Hold'), ('OVERRIDDEN', 'Approved with Override')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.budgetcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='accounts.company')),
            ],
            options={
                'ordering': ['category__code'],
            },
        ),
        migrations.AddField(
            model_name='budgetapproval',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_approvals', to='finance.budgetline'),
        ),
        migrations.CreateModel(
            name='BudgetRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('comments', models.TextField()),
                ('status', models.CharField(default='APPROVED', editable=False, max_length=20)),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_budget_revisions', to=settings.AUTH_USER_MODEL)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='finance.budgetline')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_revisions', to='accounts.company')),
            ],
            options={
                'ordering': ['-approved_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_project_budgets', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_budgets', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_project_budgets', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='finance_budget', to='projects.project')),
            ],
            options={
                'ordering': ['project__name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('comments', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_budget_transfers', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_transfers', to='accounts.company')),
                ('from_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='finance.budgetline')),
                ('to_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='finance.budgetline')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='finance.projectbudget')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('REVISION', 'Revision'), ('TRANSFER_IN', 'Transfer In'), ('TRANSFER_OUT', 'Transfer Out'), ('COMMITMENT', 'Commitment'), ('COMMITMENT_RELEASE', 'Commitment Release'), ('ACTUAL', 'Actual Expenditure'), ('ACTUAL_REVERSAL', 'Actual Reversal')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('description', models.CharField(max_length=500)),
                ('idempotency_key', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.budgetline')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_transactions', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_budget_transactions', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_transactions', to='procurement.purchaseorder')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.budgetrevision')),
                ('supplier_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_transactions', to='finance.supplierinvoice')),
                ('transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.budgettransfer')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.projectbudget')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='budgetrevision',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='finance.projectbudget'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.projectbudget'),
        ),
        migrations.AddField(
            model_name='budgetapproval',
            name='project_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_approvals', to='finance.projectbudget'),
        ),
        migrations.AddConstraint(
            model_name='budgettransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='budget_transfer_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='budgettransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='unique_company_budget_transaction_key'),
        ),
        migrations.AddConstraint(
            model_name='budgettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('amount__lt', 0), _connector='OR'), name='budget_transaction_amount_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='budgetrevision',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('amount__lt', 0), _connector='OR'), name='budget_revision_amount_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('budget', 'category'), name='unique_budget_category_line'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gte', 0)), name='budget_line_amount_nonnegative'),
        ),
    ]
