# Generated by Django 5.2.15 on 2026-08-01 09:27

import apps.finance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('finance', '0003_financialapproval_alter_budgetapproval_status_and_more'),
        ('materials', '0001_initial'),
        ('procurement', '0008_documentsequence_purchaseorder_supplier_and_more'),
        ('projects', '0004_project_site_engineers'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('WITHDRAW', 'Withdraw'), ('VERIFY', 'Verify'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('POST', 'Post'), ('REVERSE', 'Reverse'), ('CREDIT_NOTE', 'Create credit note')], max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-acted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.finance.models.invoice_attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=150)),
                ('size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(max_length=100)),
                ('credit_note_date', models.DateField()),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-credit_note_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCreditNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceItemTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='cost_centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='finance.costcentre'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='posting_idempotency_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='withholding_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('INVOICE', 'Supplier Invoice'), ('PAYMENT', 'Payment'), ('INVOICE_REVERSAL', 'Invoice Reversal'), ('PAYMENT_REVERSAL', 'Payment Reversal'), ('CREDIT_NOTE', 'Supplier Credit Note')], max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MATCHED', 'Matched'), ('MATCH_EXCEPTION', 'Match exception'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('REVERSED', 'Reversed'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='invoice_discount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('withholding_amount__gte', 0)), name='invoice_withholding_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='invoice_exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('posting_idempotency_key', ''), _negated=True), fields=('company', 'posting_idempotency_key'), name='unique_company_invoice_posting_key'),
        ),
        migrations.AddField(
            model_name='invoiceapproval',
            name='acted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceapproval',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_approvals', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='invoiceapproval',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='finance.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='invoiceattachment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_attachments', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='invoiceattachment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='finance.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='invoiceattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliercreditnote',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credit_notes', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='suppliercreditnote',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_supplier_credit_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliercreditnote',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='finance.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='suppliercreditnote',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_supplier_credit_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliercreditnote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='suppliercreditnoteitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credit_note_items', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='suppliercreditnoteitem',
            name='credit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.suppliercreditnote'),
        ),
        migrations.AddField(
            model_name='suppliercreditnoteitem',
            name='invoice_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_items', to='finance.supplierinvoiceitem'),
        ),
        migrations.AddField(
            model_name='suppliercreditnoteitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credit_note_items', to='materials.material'),
        ),
        migrations.AddField(
            model_name='suppliercreditnoteitem',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_note_items', to='finance.taxcode'),
        ),
        migrations.AddField(
            model_name='supplierinvoiceitemtax',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_item_taxes', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='supplierinvoiceitemtax',
            name='invoice_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='finance.supplierinvoiceitem'),
        ),
        migrations.AddField(
            model_name='supplierinvoiceitemtax',
            name='tax_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_item_taxes', to='finance.taxcode'),
        ),
        migrations.AddConstraint(
            model_name='invoiceapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='unique_company_invoice_approval_key'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.UniqueConstraint(fields=('company', 'supplier', 'credit_note_number'), name='unique_company_supplier_credit_note'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='unique_company_credit_note_key'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='credit_note_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='credit_note_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='credit_note_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnote',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='credit_note_exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='credit_note_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='credit_note_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='suppliercreditnoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='credit_note_item_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceitemtax',
            constraint=models.UniqueConstraint(fields=('invoice_item', 'tax_code'), name='unique_tax_per_invoice_item'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceitemtax',
            constraint=models.CheckConstraint(condition=models.Q(('taxable_amount__gte', 0)), name='invoice_item_taxable_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceitemtax',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='invoice_item_tax_value_nonnegative'),
        ),
    ]
