# Generated by Django 5.2.15 on 2026-08-01 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('finance', '0004_invoiceapproval_invoiceattachment_suppliercreditnote_and_more'),
        ('procurement', '0008_documentsequence_purchaseorder_supplier_and_more'),
        ('projects', '0004_project_site_engineers'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceMatchItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('accepted_quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rejected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('damaged_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('previously_invoiced_quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('current_invoice_quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remaining_invoiceable_quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('po_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('invoice_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('quantity_variance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('price_variance', models.DecimalField(decimal_places=2, max_digits=16)),
                ('price_variance_percent', models.DecimalField(decimal_places=4, max_digits=14)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('WITHIN_TOLERANCE', 'Within tolerance'), ('EXCEPTION', 'Exception'), ('BLOCKED', 'Blocked')], max_length=25)),
                ('explanation', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceMatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('WITHIN_TOLERANCE', 'Within tolerance'), ('EXCEPTION', 'Exception'), ('BLOCKED', 'Blocked')], max_length=25)),
                ('explanation', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=16)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('other_charges_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('credit_note_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('quantity_tolerance', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('price_tolerance', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('exception_reason', models.TextField(blank=True)),
                ('exception_approved_at', models.DateTimeField(blank=True, null=True)),
                ('exception_rejected_at', models.DateTimeField(blank=True, null=True)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-run_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='freight_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='other_charges_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='invoiceapproval',
            name='action',
            field=models.CharField(choices=[('SUBMIT', 'Submit'), ('WITHDRAW', 'Withdraw'), ('VERIFY', 'Verify'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('POST', 'Post'), ('REVERSE', 'Reverse'), ('CREDIT_NOTE', 'Create credit note'), ('APPROVE_EXCEPTION', 'Approve match exception'), ('REJECT_EXCEPTION', 'Reject match exception')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('freight_amount__gte', 0)), name='invoice_freight_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('other_charges_amount__gte', 0)), name='invoice_other_charges_nonnegative'),
        ),
        migrations.AddField(
            model_name='invoicematchitemresult',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_match_item_results', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='invoicematchitemresult',
            name='invoice_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_results', to='finance.supplierinvoiceitem'),
        ),
        migrations.AddField(
            model_name='invoicematchitemresult',
            name='purchase_order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_match_results', to='procurement.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='invoicematchrun',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_match_runs', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='invoicematchrun',
            name='exception_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_invoice_match_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicematchrun',
            name='exception_rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_invoice_match_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicematchrun',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_runs', to='finance.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='invoicematchrun',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_match_runs', to='procurement.purchaseorder'),
        ),
        migrations.AddField(
            model_name='invoicematchrun',
            name='run_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_match_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicematchitemresult',
            name='match_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_results', to='finance.invoicematchrun'),
        ),
        migrations.AddConstraint(
            model_name='invoicematchrun',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='unique_company_invoice_match_run_key'),
        ),
        migrations.AddConstraint(
            model_name='invoicematchitemresult',
            constraint=models.UniqueConstraint(fields=('match_run', 'invoice_item'), name='unique_invoice_item_per_match_run'),
        ),
    ]
