# Generated by Django 5.2.15 on 2026-08-01 10:16

import apps.finance.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_payments(apps, schema_editor):
    Payment = apps.get_model('finance', 'Payment')
    PaymentAllocation = apps.get_model('finance', 'PaymentAllocation')
    Account = apps.get_model('finance', 'Account')
    Currency = apps.get_model('finance', 'Currency')
    used_references = set()
    for payment in Payment.objects.select_related('invoice').all().iterator():
        invoice = payment.invoice
        cash = Account.objects.filter(company_id=payment.company_id, system_key='CASH').first()
        if cash is None:
            cash = Account.objects.create(
                company_id=payment.company_id, code=f'LEGACY-CASH-{payment.company_id}',
                name='Cash and Bank', account_type='ASSET', system_key='CASH', is_active=True,
            )
        currency, _ = Currency.objects.get_or_create(
            company_id=payment.company_id, code=invoice.currency,
            defaults={'name': invoice.currency, 'symbol': invoice.currency, 'is_active': True},
        )
        reference = payment.reference
        reference_key = (payment.company_id, cash.pk, reference)
        if reference and reference_key in used_references:
            reference = f'{reference[:80]}-LEGACY-{payment.pk}'
        if reference:
            used_references.add((payment.company_id, cash.pk, reference))
        Payment.objects.filter(pk=payment.pk).update(
            supplier_id=invoice.supplier_id, source_account_id=cash.pk, currency_id=currency.pk,
            status='POSTED', approved_by_id=payment.created_by_id,
            posted_by_id=payment.created_by_id, reference=reference,
        )
        PaymentAllocation.objects.get_or_create(
            company_id=payment.company_id, payment_id=payment.pk, invoice_id=invoice.pk,
            defaults={'amount': payment.amount, 'status': 'POSTED', 'created_by_id': payment.created_by_id},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('finance', '0005_invoicematchitemresult_invoicematchrun_and_more'),
        ('projects', '0004_project_site_engineers'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('POST', 'Post'), ('REVERSE', 'Reverse'), ('ALLOCATE', 'Allocate'), ('UNALLOCATE', 'Unallocate')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-acted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.finance.models.payment_attachment_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=150)),
                ('size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('APPLIED', 'Applied'), ('REVERSED', 'Reversed')], default='AUTHORIZED', max_length=20)),
                ('reason', models.TextField()),
                ('authorized_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-authorized_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='projectcost',
            name='unique_original_project_cost_per_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_finance_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='finance.currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18),
        ),
        migrations.AddField(
            model_name='payment',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_finance_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payments', to='finance.account'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_payments', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='payment',
            name='voucher_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='system_key',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash/Bank'), ('ACCOUNTS_PAYABLE', 'Accounts Payable'), ('INVENTORY', 'Inventory'), ('PROJECT_COST', 'Project Cost'), ('SUPPLIER_ADVANCE', 'Supplier Advance')], max_length=40),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.supplierinvoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='finance.journalentry'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='payment_exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('company', 'source_account', 'reference'), name='unique_payment_account_reference'),
        ),
        migrations.AddConstraint(
            model_name='projectcost',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reversal', False)), fields=('payment', 'supplier_invoice'), name='unique_project_cost_per_payment_invoice'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='finance.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='paymentapproval',
            name='acted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentapproval',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_approvals', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='paymentapproval',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='paymentattachment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attachments', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='paymentattachment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='paymentattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplieradvance',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_supplier_advances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplieradvance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_advances', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='supplieradvance',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_advance', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='supplieradvance',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='suppliers.supplier'),
        ),
        migrations.RunPython(migrate_legacy_payments, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice'), name='unique_invoice_per_payment'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_allocation_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='unique_company_payment_approval_key'),
        ),
        migrations.AddConstraint(
            model_name='supplieradvance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='supplier_advance_positive'),
        ),
    ]
