# Generated by Django 5.2.15 on 2026-08-01 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('finance', '0006_paymentallocation_paymentapproval_paymentattachment_and_more'),
        ('procurement', '0009_alter_documentsequence_document_type_and_more'),
        ('warehouse', '0006_alter_stockmovement_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandedCostDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('allocation_method', models.CharField(choices=[('QUANTITY', 'Quantity'), ('WEIGHT', 'Weight'), ('MATERIAL_VALUE', 'Material value'), ('EQUAL', 'Equal distribution'), ('MANUAL', 'Manual allocation')], max_length=25)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('base_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_landed_cost_documents', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_documents', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_landed_cost_documents', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_documents', to='finance.currency')),
                ('goods_received_notes', models.ManyToManyField(blank=True, related_name='landed_cost_documents', to='procurement.goodsreceivednote')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_landed_cost_documents', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_document', to='finance.landedcostdocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandedCostApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('POST', 'Post'), ('REVERSE', 'Reverse')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_approvals', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_approvals', to='accounts.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='finance.landedcostdocument')),
            ],
            options={
                'ordering': ['-acted_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LandedCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('basis_weight', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('basis_value', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_allocations', to='accounts.company')),
                ('goods_received_note_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_allocations', to='procurement.goodsreceivednoteitem')),
                ('receipt_movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_allocations', to='warehouse.stockmovement')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_allocation', to='finance.landedcostallocation')),
                ('valuation_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_valuation_allocation', to='warehouse.stockmovement')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.landedcostdocument')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LandedCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('TRANSPORT', 'Transport'), ('LOADING_OFFLOADING', 'Loading and offloading'), ('INSURANCE', 'Insurance'), ('HANDLING', 'Handling'), ('NON_REFUNDABLE_TAX', 'Non-refundable tax'), ('OTHER', 'Other approved cost')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_items', to='accounts.company')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finance.landedcostdocument')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_items', to='finance.taxcode')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='landedcostdocument',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_company_landed_cost_number'),
        ),
        migrations.AddConstraint(
            model_name='landedcostdocument',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='landed_cost_exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='landedcostdocument',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='landed_cost_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='landedcostdocument',
            constraint=models.CheckConstraint(condition=models.Q(('base_total_amount__gte', 0)), name='landed_cost_base_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='landedcostapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='unique_company_landed_cost_action_key'),
        ),
        migrations.AddConstraint(
            model_name='landedcostallocation',
            constraint=models.UniqueConstraint(fields=('document', 'goods_received_note_item'), name='unique_landed_cost_grn_item_allocation'),
        ),
        migrations.AddConstraint(
            model_name='landedcostallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gte', 0)), name='landed_cost_allocation_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='landedcostallocation',
            constraint=models.CheckConstraint(condition=models.Q(('basis_quantity__gte', 0)), name='landed_cost_basis_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='landedcostallocation',
            constraint=models.CheckConstraint(condition=models.Q(('basis_weight__gte', 0)), name='landed_cost_basis_weight_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='landedcostallocation',
            constraint=models.CheckConstraint(condition=models.Q(('basis_value__gte', 0)), name='landed_cost_basis_value_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='landedcostitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='landed_cost_item_amount_positive'),
        ),
    ]
