# Generated by Django 5.2.15 on 2026-08-01 11:42

import apps.finance.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('finance', '0007_landedcostdocument_landedcostapproval_and_more'),
        ('projects', '0004_project_site_engineers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='system_key',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash/Bank'), ('ACCOUNTS_PAYABLE', 'Accounts Payable'), ('INVENTORY', 'Inventory'), ('PROJECT_COST', 'Project Cost'), ('SUPPLIER_ADVANCE', 'Supplier Advance'), ('STAFF_ADVANCE', 'Staff Advance')], max_length=40),
        ),
        migrations.AlterField(
            model_name='financedocumentsequence',
            name='document_type',
            field=models.CharField(choices=[('INV', 'Supplier Invoice'), ('PAY', 'Payment'), ('JE', 'Journal Entry'), ('EXP', 'Expense Claim'), ('SADV', 'Staff Advance')], max_length=10),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('INVOICE', 'Supplier Invoice'), ('PAYMENT', 'Payment'), ('INVOICE_REVERSAL', 'Invoice Reversal'), ('PAYMENT_REVERSAL', 'Payment Reversal'), ('CREDIT_NOTE', 'Supplier Credit Note'), ('EXPENSE', 'Expense Claim'), ('STAFF_ADVANCE', 'Staff Advance'), ('ADVANCE_RETIREMENT', 'Advance Retirement'), ('PETTY_CASH', 'Petty Cash'), ('EXPENSE_REVERSAL', 'Expense Reversal'), ('ADVANCE_REVERSAL', 'Staff Advance Reversal')], max_length=30),
        ),
        migrations.CreateModel(
            name='AdvanceRetirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_retired', models.DecimalField(decimal_places=2, max_digits=18)),
                ('retirement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reason', models.TextField()),
                ('idempotency_key', models.CharField(max_length=100)),
                ('is_reversal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_retirements', to='accounts.company')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advance_retirement', to='finance.journalentry')),
                ('retired_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_retirements', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.advanceretirement')),
            ],
            options={
                'ordering': ['-retirement_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='advance_retirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_transactions', to='finance.advanceretirement'),
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('is_petty_cash', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_accounts', to='finance.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_accounts', to='accounts.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_accounts', to='finance.currency')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('category_type', models.CharField(choices=[('TRANSPORT', 'Transport'), ('LOADING_OFFLOADING', 'Loading and offloading'), ('EQUIPMENT_HIRE', 'Equipment hire'), ('FUEL', 'Fuel'), ('SITE_CONSUMABLES', 'Site consumables'), ('EMERGENCY_MATERIALS', 'Emergency material purchases'), ('ACCOMMODATION', 'Accommodation'), ('MISCELLANEOUS', 'Miscellaneous project expenses')], max_length=30)),
                ('is_overhead', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='finance.budgetcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='accounts.company')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='finance.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='advanceretirement',
            name='expense_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_retirements', to='finance.expensecategory'),
        ),
        migrations.CreateModel(
            name='ExpenseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
                ('claim_date', models.DateField(default=django.utils.timezone.localdate)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('base_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('posting_idempotency_key', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_expense_claims', to=settings.AUTH_USER_MODEL)),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='finance.cashaccount')),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='accounts.company')),
                ('cost_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='finance.costcentre')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expense_claims', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='finance.currency')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claim', to='finance.journalentry')),
                ('overhead_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overhead_claims', to='finance.expensecategory')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_expense_claims', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claims', to='projects.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_expense_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-claim_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='budgettransaction',
            name='expense_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_transactions', to='finance.expenseclaim'),
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_items', to='finance.expensecategory')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finance.expenseclaim')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_items', to='accounts.company')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseReceiptAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.finance.models.expense_receipt_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=150)),
                ('size', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='finance.expenseclaim')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_receipts', to='accounts.company')),
                ('expense_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='finance.expenseitem')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
                ('advance_date', models.DateField(default=django.utils.timezone.localdate)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('RETIRED', 'Retired'), ('CLOSED', 'Closed'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='DRAFT', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('posting_idempotency_key', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_staff_advances', to=settings.AUTH_USER_MODEL)),
                ('cash_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_advances', to='finance.cashaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_advances', to='accounts.company')),
                ('cost_centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_advances', to='finance.costcentre')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_staff_advances', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_advances', to='finance.currency')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_advance', to='finance.journalentry')),
                ('overhead_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overhead_advances', to='finance.expensecategory')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_staff_advances', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_advances', to='projects.project')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_advances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-advance_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PettyCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DISBURSEMENT', 'Expense disbursement'), ('ADVANCE', 'Staff advance'), ('REFUND', 'Advance refund'), ('REPLENISHMENT', 'Replenishment'), ('REVERSAL', 'Reversal')], max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_effect', models.DecimalField(decimal_places=2, max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('transaction_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='POSTED', max_length=20)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('advance_retirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_transactions', to='finance.advanceretirement')),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.cashaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_transactions', to='accounts.company')),
                ('expense_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_transactions', to='finance.expenseclaim')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_transaction', to='finance.journalentry')),
                ('original_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_transaction', to='finance.pettycashtransaction')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('staff_advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_transactions', to='finance.staffadvance')),
            ],
            options={
                'ordering': ['-transaction_date', '-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMIT', 'Submit'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('PAY', 'Pay'), ('RETIRE', 'Retire'), ('REPLENISH', 'Replenish'), ('REVERSE', 'Reverse')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('acted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_approvals', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_approvals', to='accounts.company')),
                ('expense_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='finance.expenseclaim')),
                ('petty_cash_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='finance.pettycashtransaction')),
                ('staff_advance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='finance.staffadvance')),
            ],
            options={
                'ordering': ['-acted_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='advanceretirement',
            name='advance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retirements', to='finance.staffadvance'),
        ),
        migrations.AddConstraint(
            model_name='cashaccount',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_cash_account_code'),
        ),
        migrations.AddConstraint(
            model_name='cashaccount',
            constraint=models.UniqueConstraint(fields=('company', 'account'), name='unique_company_cash_ledger_account'),
        ),
        migrations.AddConstraint(
            model_name='cashaccount',
            constraint=models.CheckConstraint(condition=models.Q(('opening_balance__gte', 0)), name='cash_opening_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_expense_category'),
        ),
        migrations.AddConstraint(
            model_name='expenseclaim',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_company_expense_claim_number'),
        ),
        migrations.AddConstraint(
            model_name='expenseclaim',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='unique_company_expense_claim_key'),
        ),
        migrations.AddConstraint(
            model_name='expenseclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_reference', ''), _negated=True), fields=('company', 'cash_account', 'payment_reference'), name='unique_expense_reimbursement_reference'),
        ),
        migrations.AddConstraint(
            model_name='expenseclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('posting_idempotency_key', ''), _negated=True), fields=('company', 'posting_idempotency_key'), name='unique_expense_posting_key'),
        ),
        migrations.AddConstraint(
            model_name='expenseclaim',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='expense_exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='expenseclaim',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='expense_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='expenseclaim',
            constraint=models.CheckConstraint(condition=models.Q(('base_total_amount__gte', 0)), name='expense_base_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='expenseclaim',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0)), name='expense_amount_paid_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='expenseclaim',
            constraint=models.CheckConstraint(condition=models.Q(('project__isnull', False), ('cost_centre__isnull', False), ('overhead_category__isnull', False), _connector='OR'), name='expense_claim_has_destination'),
        ),
        migrations.AddConstraint(
            model_name='expenseitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_item_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='staffadvance',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_company_staff_advance_number'),
        ),
        migrations.AddConstraint(
            model_name='staffadvance',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='unique_company_staff_advance_key'),
        ),
        migrations.AddConstraint(
            model_name='staffadvance',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_reference', ''), _negated=True), fields=('company', 'cash_account', 'payment_reference'), name='unique_staff_advance_payment_reference'),
        ),
        migrations.AddConstraint(
            model_name='staffadvance',
            constraint=models.UniqueConstraint(condition=models.Q(('posting_idempotency_key', ''), _negated=True), fields=('company', 'posting_idempotency_key'), name='unique_staff_advance_posting_key'),
        ),
        migrations.AddConstraint(
            model_name='staffadvance',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='staff_advance_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='staffadvance',
            constraint=models.CheckConstraint(condition=models.Q(('base_amount__gte', 0)), name='staff_advance_base_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='staffadvance',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='staff_advance_exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='staffadvance',
            constraint=models.CheckConstraint(condition=models.Q(('project__isnull', False), ('cost_centre__isnull', False), ('overhead_category__isnull', False), _connector='OR'), name='staff_advance_has_destination'),
        ),
        migrations.AddConstraint(
            model_name='pettycashtransaction',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='unique_company_petty_cash_key'),
        ),
        migrations.AddConstraint(
            model_name='pettycashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='petty_cash_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='pettycashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('exchange_rate__gt', 0)), name='petty_cash_exchange_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='pettycashtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('balance_effect__gt', 0), ('balance_effect__lt', 0), _connector='OR'), name='petty_cash_effect_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='expenseapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('company', 'idempotency_key'), name='unique_company_expense_approval_key'),
        ),
        migrations.AddConstraint(
            model_name='expenseapproval',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expense_claim__isnull', False), ('petty_cash_transaction__isnull', True), ('staff_advance__isnull', True)), models.Q(('expense_claim__isnull', True), ('petty_cash_transaction__isnull', True), ('staff_advance__isnull', False)), models.Q(('expense_claim__isnull', True), ('petty_cash_transaction__isnull', False), ('staff_advance__isnull', True)), _connector='OR'), name='expense_approval_one_target'),
        ),
        migrations.AddConstraint(
            model_name='advanceretirement',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='unique_company_advance_retirement_key'),
        ),
        migrations.AddConstraint(
            model_name='advanceretirement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_spent__gte', 0)), name='advance_spent_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='advanceretirement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_refunded__gte', 0)), name='advance_refund_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='advanceretirement',
            constraint=models.CheckConstraint(condition=models.Q(('total_retired__gt', 0)), name='advance_retired_positive'),
        ),
        migrations.AddConstraint(
            model_name='advanceretirement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_reversal', False), ('reversal_of__isnull', True)), models.Q(('is_reversal', True), ('reversal_of__isnull', False)), _connector='OR'), name='advance_retirement_reversal_consistency'),
        ),
    ]
