# Generated by Django 5.2.15 on 2026-08-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_account_system_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('INVOICE', 'Supplier Invoice'), ('PAYMENT', 'Payment'), ('INVOICE_REVERSAL', 'Invoice Reversal'), ('PAYMENT_REVERSAL', 'Payment Reversal'), ('CREDIT_NOTE', 'Supplier Credit Note'), ('EXPENSE', 'Expense Claim'), ('STAFF_ADVANCE', 'Staff Advance'), ('ADVANCE_RETIREMENT', 'Advance Retirement'), ('ADVANCE_RETIREMENT_REVERSAL', 'Advance Retirement Reversal'), ('PETTY_CASH', 'Petty Cash'), ('PETTY_CASH_REVERSAL', 'Petty Cash Reversal'), ('EXPENSE_REVERSAL', 'Expense Reversal'), ('ADVANCE_REVERSAL', 'Staff Advance Reversal')], max_length=30),
        ),
    ]
