# Generated by Django 5.2.15 on 2026-08-01 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('finance', '0009_alter_journalentry_source_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_key', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['mapping_key'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='JournalReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('idempotency_key', models.CharField(max_length=100)),
                ('reversed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reversed_at'],
            },
        ),
        migrations.CreateModel(
            name='PostingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GRN_RECEIPT', 'GRN inventory receipt'), ('SUPPLIER_INVOICE', 'Supplier invoice'), ('SUPPLIER_PAYMENT', 'Supplier payment'), ('PROJECT_ISSUE', 'Material issue to project'), ('INVENTORY_ADJUSTMENT', 'Inventory adjustment'), ('INVENTORY_WRITE_OFF', 'Inventory write-off'), ('SUPPLIER_RETURN', 'Supplier return'), ('CREDIT_NOTE', 'Credit note'), ('LANDED_COST', 'Landed cost'), ('PROJECT_EXPENSE', 'Project expense'), ('PETTY_CASH', 'Petty-cash transaction')], max_length=40)),
                ('name', models.CharField(max_length=150)),
                ('debit_mapping_key', models.CharField(max_length=50)),
                ('credit_mapping_key', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_type'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
            ],
            options={
                'verbose_name': 'chart of account',
                'verbose_name_plural': 'chart of accounts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('finance.account',),
        ),
        migrations.RemoveConstraint(
            model_name='journalentry',
            name='unique_finance_source_journal',
        ),
        migrations.AddField(
            model_name='account',
            name='allow_manual_posting',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.account'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], default='POSTED', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='system_key',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash/Bank'), ('ACCOUNTS_PAYABLE', 'Accounts Payable'), ('INVENTORY', 'Inventory'), ('PROJECT_COST', 'Project Cost'), ('SUPPLIER_ADVANCE', 'Supplier Advance'), ('STAFF_ADVANCE', 'Staff Advance'), ('GRN_CLEARING', 'GRN Clearing'), ('INVENTORY_ADJUSTMENT', 'Inventory Adjustment'), ('INVENTORY_WRITE_OFF', 'Inventory Write-off'), ('LANDED_COST_CLEARING', 'Landed Cost Clearing')], max_length=40),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('INVOICE', 'Supplier Invoice'), ('PAYMENT', 'Payment'), ('INVOICE_REVERSAL', 'Invoice Reversal'), ('PAYMENT_REVERSAL', 'Payment Reversal'), ('CREDIT_NOTE', 'Supplier Credit Note'), ('EXPENSE', 'Expense Claim'), ('STAFF_ADVANCE', 'Staff Advance'), ('ADVANCE_RETIREMENT', 'Advance Retirement'), ('ADVANCE_RETIREMENT_REVERSAL', 'Advance Retirement Reversal'), ('PETTY_CASH', 'Petty Cash'), ('PETTY_CASH_REVERSAL', 'Petty Cash Reversal'), ('EXPENSE_REVERSAL', 'Expense Reversal'), ('ADVANCE_REVERSAL', 'Staff Advance Reversal'), ('MANUAL', 'Manual Journal'), ('GRN', 'Goods Received Note'), ('STOCK_MOVEMENT', 'Stock Movement'), ('LANDED_COST', 'Landed Cost'), ('JOURNAL_REVERSAL', 'Journal Reversal')], max_length=30),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_mappings', to='finance.account'),
        ),
        migrations.AddField(
            model_name='accountmapping',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_mappings', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_fiscal_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalperiod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_periods', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='fiscal_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='finance.fiscalperiod'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('source_object_id__isnull', False)), fields=('company', 'source_type', 'source_object_id'), name='unique_finance_source_journal'),
        ),
        migrations.AddField(
            model_name='journalreversal',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_reversals', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='journalreversal',
            name='original_journal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal_record', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='journalreversal',
            name='reversal_journal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reverses_record', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='journalreversal',
            name='reversed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_reversals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postingrule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posting_rules', to='accounts.company'),
        ),
        migrations.AddConstraint(
            model_name='accountmapping',
            constraint=models.UniqueConstraint(fields=('company', 'mapping_key'), name='unique_company_account_mapping_key'),
        ),
        migrations.AddConstraint(
            model_name='fiscalperiod',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_fiscal_period_name'),
        ),
        migrations.AddConstraint(
            model_name='fiscalperiod',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='fiscal_period_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='journalreversal',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='unique_company_journal_reversal_key'),
        ),
        migrations.AddConstraint(
            model_name='postingrule',
            constraint=models.UniqueConstraint(fields=('company', 'event_type'), name='unique_company_posting_rule_event'),
        ),
    ]
