# Generated by Django 5.2.15 on 2026-08-01 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
        ('finance', '0013_backfill_journal_fiscal_periods'),
        ('procurement', '0009_alter_documentsequence_document_type_and_more'),
        ('projects', '0004_project_site_engineers'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSyncReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.UUIDField()),
                ('record_type', models.CharField(max_length=50)),
                ('idempotency_key', models.CharField(max_length=150)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_data', models.JSONField(default=dict)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='version',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='version',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='landedcostdocument',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landedcostdocument',
            name='version',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='version',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='version',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='staffadvance',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffadvance',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffadvance',
            name='version',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='version',
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
        migrations.AddConstraint(
            model_name='expenseclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('company', 'client_uuid'), name='unique_company_expense_client_uuid'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('company', 'client_uuid'), name='unique_company_journal_client_uuid'),
        ),
        migrations.AddConstraint(
            model_name='landedcostdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('company', 'client_uuid'), name='unique_company_landed_client_uuid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('company', 'client_uuid'), name='unique_company_payment_client_uuid'),
        ),
        migrations.AddConstraint(
            model_name='projectbudget',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('company', 'client_uuid'), name='unique_company_budget_client_uuid'),
        ),
        migrations.AddConstraint(
            model_name='staffadvance',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('company', 'client_uuid'), name='unique_company_advance_client_uuid'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('client_uuid__isnull', False)), fields=('company', 'client_uuid'), name='unique_company_invoice_client_uuid'),
        ),
        migrations.AddField(
            model_name='financesyncreceipt',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_sync_receipts', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='financesyncreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_sync_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='financesyncreceipt',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='unique_finance_sync_company_key'),
        ),
    ]
