# Generated by Django 5.2.15 on 2026-08-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_financesyncreceipt_expenseclaim_client_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='system_key',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash/Bank'), ('ACCOUNTS_PAYABLE', 'Accounts Payable'), ('INVENTORY', 'Inventory'), ('PROJECT_COST', 'Project Cost'), ('SUPPLIER_ADVANCE', 'Supplier Advance'), ('STAFF_ADVANCE', 'Staff Advance'), ('GRN_CLEARING', 'GRN Clearing'), ('INVENTORY_ADJUSTMENT', 'Inventory Adjustment'), ('INVENTORY_WRITE_OFF', 'Inventory Write-off'), ('LANDED_COST_CLEARING', 'Landed Cost Clearing'), ('REALIZED_FX', 'Realized Foreign Exchange Gain/Loss')], max_length=40),
        ),
    ]
