# Generated by Django 5.2.15 on 2026-08-15 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_active_session_id_and_more'),
        ('finance', '0016_budgetapproval_return_reason'),
        ('projects', '0005_approvaldelegation_projectstaffassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalMatrixRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('PURCHASE_REQUEST', 'Purchase request'), ('PURCHASE_ORDER', 'Purchase order'), ('SUPPLIER_INVOICE', 'Supplier invoice'), ('PAYMENT', 'Payment'), ('BUDGET', 'Budget'), ('JOURNAL', 'Journal')], max_length=30)),
                ('stage', models.CharField(choices=[('TECHNICAL', 'Technical approval'), ('FINANCE', 'Finance review'), ('FINAL', 'Final approval')], max_length=20)),
                ('approver_role', models.CharField(choices=[('site_engineer', 'Site Engineer'), ('storekeeper', 'Storekeeper'), ('project_manager', 'Project Manager'), ('procurement_officer', 'Procurement Officer'), ('finance_officer', 'Finance Officer'), ('finance_manager', 'Finance Manager'), ('finance_viewer', 'Finance Viewer'), ('admin', 'Admin')], max_length=30)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('due_hours', models.PositiveIntegerField(default=24)),
                ('escalation_hours', models.PositiveIntegerField(default=48)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_matrix_rules', to='finance.budgetcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_matrix_rules', to='accounts.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_matrix_rules', to='projects.project')),
            ],
            options={
                'ordering': ['document_type', 'stage', 'minimum_amount'],
            },
        ),
    ]
