# Generated by Django 5.2.15 on 2026-08-15 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_active_session_id_and_more'),
        ('finance', '0017_approvalmatrixrule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('reference', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('UNRECONCILED', 'Unreconciled'), ('MATCHED', 'Matched'), ('IGNORED', 'Ignored')], default='UNRECONCILED', max_length=20)),
                ('match_notes', models.TextField(blank=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_lines', to='finance.cashaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statement_lines', to='accounts.company')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_bank_statement_lines', to=settings.AUTH_USER_MODEL)),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matched_bank_statement_lines', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_line', to='finance.payment')),
            ],
            options={
                'ordering': ['-statement_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('cash_account', 'statement_date', 'reference'), name='unique_statement_line_reference_per_account_date'), models.CheckConstraint(condition=models.Q(('amount__gt', 0), ('amount__lt', 0), _connector='OR'), name='bank_statement_line_amount_nonzero')],
            },
        ),
    ]
