# Generated by Django 5.2.15 on 2026-08-15 08:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_active_session_id_and_more'),
        ('finance', '0018_bankstatementline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='system_key',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash/Bank'), ('ACCOUNTS_PAYABLE', 'Accounts Payable'), ('INVENTORY', 'Inventory'), ('PROJECT_COST', 'Project Cost'), ('SUPPLIER_ADVANCE', 'Supplier Advance'), ('STAFF_ADVANCE', 'Staff Advance'), ('GRN_CLEARING', 'GRN Clearing'), ('INVENTORY_ADJUSTMENT', 'Inventory Adjustment'), ('INVENTORY_WRITE_OFF', 'Inventory Write-off'), ('LANDED_COST_CLEARING', 'Landed Cost Clearing'), ('REALIZED_FX', 'Realized Foreign Exchange Gain/Loss'), ('RECOVERABLE_VAT', 'Recoverable VAT'), ('WITHHOLDING_TAX_PAYABLE', 'Withholding Tax Payable')], max_length=40),
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('RELEASED', 'Released to ledger'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_batches', to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_batches', to='finance.currency')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_batches', to='finance.account')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='finance.paymentbatch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_batch_items', to='accounts.company')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_items', to='finance.payment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentbatch',
            constraint=models.UniqueConstraint(fields=('company', 'number'), name='unique_company_payment_batch_number'),
        ),
        migrations.AddConstraint(
            model_name='paymentbatchitem',
            constraint=models.UniqueConstraint(fields=('batch', 'payment'), name='unique_payment_per_batch'),
        ),
    ]
