# Generated by Django 5.2.15 on 2026-08-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_active_session_id_and_more'),
        ('finance', '0019_alter_account_system_key_paymentbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='document_retention_years',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='require_invoice_attachment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='require_payment_attachment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='financesettings',
            constraint=models.CheckConstraint(condition=models.Q(('document_retention_years__gte', 1)), name='finance_document_retention_minimum_one_year'),
        ),
    ]
