# Generated by Django 5.2.15 on 2026-08-17 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_supplierinvoice_work_order'),
        ('workorders', '0002_alter_workorder_project_workordersite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinvoice',
            name='work_order_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='workorders.workordersite'),
        ),
    ]
