# Generated by Django 5.2.15 on 2026-08-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finance', '0022_supplierinvoice_work_order_site'),
        ('warehouse', '0005_warehouse_stock_valuation'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettransaction',
            name='stock_movement',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='budget_transactions',
                to='warehouse.stockmovement',
            ),
        ),
    ]
