# Generated by Django 5.2.15 on 2026-09-04 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_budgettransaction_stock_movement'),
        ('materials', '0001_initial'),
        ('procurement', '0023_purchaserequest_manager_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoices', to='procurement.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='supplierinvoiceitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_items', to='materials.material'),
        ),
        migrations.AlterField(
            model_name='supplierinvoiceitem',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_items', to='procurement.purchaseorderitem'),
        ),
    ]
