# Generated by Django 5.2.15 on 2026-09-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_alter_supplierinvoice_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='allow_unbudgeted_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='budget_control_mode',
            field=models.CharField(choices=[('off', 'Off'), ('warn', 'Warn'), ('block', 'Block')], default='warn', max_length=8),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='invoice_tracking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='matching_mode',
            field=models.CharField(choices=[('two_way', 'Two-way'), ('three_way', 'Three-way')], default='three_way', max_length=10),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='payment_tracking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='require_invoice_matching',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='soft_finance_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
