# Generated by Django 5.2.15 on 2026-09-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_workflowconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmatrixrule',
            name='document_type',
            field=models.CharField(choices=[('PURCHASE_REQUEST', 'Material request'), ('PURCHASE_ORDER', 'Purchase order'), ('SUPPLIER_INVOICE', 'Supplier invoice'), ('PAYMENT', 'Payment'), ('BUDGET', 'Budget'), ('JOURNAL', 'Journal')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workflowconfirmation',
            name='document_type',
            field=models.CharField(choices=[('PURCHASE_REQUEST', 'Material request'), ('STOCK_ISSUE', 'Stock issue'), ('PURCHASE_ORDER', 'Purchase order'), ('PO_DISPATCH', 'Purchase order dispatch'), ('WAREHOUSE_RECEIPT', 'Warehouse receipt'), ('SITE_RECEIPT', 'Direct-to-site receipt'), ('OPENING_STOCK', 'Opening stock import'), ('SUPPLIER_INVOICE', 'Supplier invoice'), ('PAYMENT', 'Payment')], max_length=30),
        ),
    ]
