export const qk = {
  finance: ['finance'] as const,
  dashboard: ['dashboard'] as const,
  me: ['me'] as const,
  users: (params?: object) => ['users', params] as const,
  categories: (params?: object) => ['categories', params] as const,
  projects: (params?: object) => ['projects', params] as const,
  project: (id: string | number) => ['projects', id] as const,
  materials: (params?: object) => ['materials', params] as const,
  movements: (params?: object) => ['stock-movements', params] as const,
  suppliers: (params?: object) => ['suppliers', params] as const,
  purchaseRequests: (params?: object) => ['purchase-requests', params] as const,
  purchaseOrders: (params?: object) => ['purchase-orders', params] as const,
  goodsReceivedNotes: (params?: object) => ['goods-received-notes', params] as const,
  supplierClaims: (params?: object) => ['supplier-claims', params] as const,
  notifications: (params?: object) => ['notifications', params] as const,
  unreadCount: ['notifications', 'unread-count'] as const,
  workflowBadges: ['workflow-badges'] as const,
  chatMessages: (projectId?: string | number) => ['chat', projectId] as const,
  financeDashboard: (params?: object) => ['finance', 'dashboard', params] as const,
  financeBudgets: (params?: object) => ['finance', 'budgets', params] as const,
  financeApprovals: (params?: object) => ['finance', 'approvals', params] as const,
  financeInvoices: (params?: object) => ['finance', 'invoices', params] as const,
  financePayments: (params?: object) => ['finance', 'payments', params] as const,
  financeExpenses: (params?: object) => ['finance', 'expenses', params] as const,
  financeAdvances: (params?: object) => ['finance', 'advances', params] as const,
  financeAccounts: (params?: object) => ['finance', 'accounts', params] as const,
  financeJournals: (params?: object) => ['finance', 'journals', params] as const,
  financeReport: (slug: string, params?: object) => ['finance', 'reports', slug, params] as const,
  financePaymentBatches: (params?: object) => ['finance', 'payment-batches', params] as const,
  financeStatementLines: (params?: object) => ['finance', 'statement-lines', params] as const,
  financePeriods: (params?: object) => ['finance', 'periods', params] as const,
  workOrderMetrics: ['work-orders', 'metrics'] as const,
  workOrderActionQueue: ['work-orders', 'action-queue'] as const,
  purchaseRequestActionQueue: (params?: object) => ['purchase-requests', 'action-queue', params] as const,
  purchaseOrderActionQueue: (params?: object) => ['purchase-orders', 'action-queue', params] as const,
  supplierClaimActionQueue: (params?: object) => ['supplier-claims', 'action-queue', params] as const,
};
