# Generated by Django 5.2.15 on 2026-07-29 13:20

import django.db.models.deletion
from django.db import migrations, models


def link_existing_purchase_order_movements(apps, schema_editor):
    StockMovement = apps.get_model('warehouse', 'StockMovement')
    PurchaseOrderItem = apps.get_model('procurement', 'PurchaseOrderItem')

    movements = StockMovement.objects.filter(
        purchase_order__isnull=False,
        purchase_order_item__isnull=True,
    )
    for movement in movements.iterator():
        item = PurchaseOrderItem.objects.filter(
            purchase_order_id=movement.purchase_order_id,
            material_id=movement.material_id,
        ).first()
        if item and not StockMovement.objects.filter(purchase_order_item_id=item.id).exists():
            movement.purchase_order_item_id = item.id
            movement.save(update_fields=['purchase_order_item'])


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
        ('procurement', '0008_documentsequence_purchaseorder_supplier_and_more'),
        ('warehouse', '0002_alter_stockmovement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement', to='procurement.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='procurement.purchaserequest'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_request_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement', to='procurement.purchaserequestitem'),
        ),
        migrations.RunPython(
            link_existing_purchase_order_movements,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='materials.material'),
        ),
    ]
