# Generated by Django 5.2.15 on 2026-08-01 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_alter_documentsequence_document_type_and_more'),
        ('warehouse', '0003_stockmovement_purchase_order_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='procurement.purchaseorderitem'),
        ),
    ]
