# Generated by Django 5.2.15 on 2026-08-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_warehouse_stock_valuation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='transaction_type',
            field=models.CharField(choices=[('LEGACY', 'Legacy movement'), ('OPENING', 'Opening balance'), ('RECEIPT', 'Valued receipt'), ('PROJECT_ISSUE', 'Project issue'), ('PROJECT_RETURN', 'Project return'), ('SUPPLIER_RETURN', 'Supplier return'), ('DAMAGE', 'Damage'), ('WRITE_OFF', 'Write off'), ('QUANTITY_ADJUSTMENT', 'Quantity adjustment'), ('VALUATION_ADJUSTMENT', 'Valuation adjustment'), ('LANDED_COST', 'Landed cost'), ('LANDED_COST_REVERSAL', 'Landed cost reversal')], default='LEGACY', max_length=30),
        ),
    ]
