from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('warehouse', '0007_warehouse_project_site_store'), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.AlterField(model_name='stockmovement', name='transaction_type', field=models.CharField(choices=[('LEGACY','Legacy movement'),('OPENING','Opening balance'),('RECEIPT','Valued receipt'),('PROJECT_ISSUE','Project issue'),('PROJECT_RETURN','Project return'),('SITE_TRANSFER_OUT','Transfer dispatched to site'),('SITE_TRANSFER_IN','Transfer acknowledged at site'),('SITE_CONSUMPTION','Site consumption'),('SITE_RETURN_OUT','Return dispatched from site'),('SITE_RETURN_IN','Return received into warehouse'),('SUPPLIER_RETURN','Supplier return'),('DAMAGE','Damage'),('WRITE_OFF','Write off'),('QUANTITY_ADJUSTMENT','Quantity adjustment'),('VALUATION_ADJUSTMENT','Valuation adjustment'),('LANDED_COST','Landed cost'),('LANDED_COST_REVERSAL','Landed cost reversal')], default='LEGACY', max_length=30)),
        migrations.CreateModel(name='SiteTransfer', fields=[
            ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('quantity', models.DecimalField(decimal_places=2, max_digits=18)), ('status', models.CharField(choices=[('DISPATCHED','Dispatched'),('ACKNOWLEDGED','Acknowledged')], default='DISPATCHED', max_length=16)), ('reason', models.TextField()), ('dispatched_at', models.DateTimeField(auto_now_add=True)), ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
            ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acknowledged_site_transfers', to=settings.AUTH_USER_MODEL)), ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_transfers', to='accounts.company')), ('destination_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_site_transfers', to='warehouse.warehouse')), ('dispatched_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatched_site_transfers', to=settings.AUTH_USER_MODEL)), ('inbound_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_site_transfer', to='warehouse.stockmovement')), ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_transfers', to='materials.material')), ('outbound_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_site_transfer', to='warehouse.stockmovement')), ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_transfers', to='projects.project')), ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_site_transfers', to='warehouse.warehouse')),
        ], options={'ordering':['-dispatched_at']}),
    ]
