# Generated by Django 5.2.15 on 2026-08-15 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_sitetransfer_stockmovement_site_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_locations', to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['warehouse__name', 'code'],
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_warehouse_bin_code')],
            },
        ),
    ]
