# Generated by Django 5.2.15 on 2026-08-17 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectsite'),
        ('warehouse', '0012_stockmovement_work_order_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='project_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='projects.projectsite'),
        ),
    ]
