# Generated by Django 5.2.15 on 2026-09-25 15:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_active_session_device_id'),
        ('materials', '0001_initial'),
        ('projects', '0007_projectsite_closed_at_projectsite_closed_by_and_more'),
        ('warehouse', '0013_warehouse_project_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='transaction_type',
            field=models.CharField(choices=[('EXTERNAL_RECEIPT', 'External transfer receipt'), ('EXTERNAL_RETURN', 'External transfer return / reversal'), ('LEGACY', 'Legacy movement'), ('OPENING', 'Opening balance'), ('RECEIPT', 'Valued receipt'), ('PROJECT_ISSUE', 'Project issue'), ('PROJECT_RETURN', 'Project return'), ('SITE_TRANSFER_OUT', 'Transfer dispatched to site'), ('SITE_TRANSFER_IN', 'Transfer acknowledged at site'), ('SITE_CONSUMPTION', 'Site consumption'), ('SITE_RETURN_OUT', 'Return dispatched from site'), ('SITE_RETURN_IN', 'Return received into warehouse'), ('SUPPLIER_RETURN', 'Supplier return'), ('DAMAGE', 'Damage'), ('WRITE_OFF', 'Write off'), ('QUANTITY_ADJUSTMENT', 'Quantity adjustment'), ('VALUATION_ADJUSTMENT', 'Valuation adjustment'), ('LANDED_COST', 'Landed cost'), ('LANDED_COST_REVERSAL', 'Landed cost reversal')], default='LEGACY', max_length=30),
        ),
        migrations.CreateModel(
            name='ExternalMoveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=160)),
                ('reference', models.CharField(max_length=100)),
                ('sender_key', models.CharField(editable=False, max_length=160)),
                ('reference_key', models.CharField(editable=False, max_length=100)),
                ('ownership', models.CharField(choices=[('PERMANENT', 'Permanent transfer'), ('BORROWED', 'Borrowed')], max_length=12)),
                ('expected_date', models.DateField(default=django.utils.timezone.localdate)),
                ('return_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ExternalMoveLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bin_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.binlocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='warehouse.externalmoveorder')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ExternalReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting admin'), ('POSTED', 'Posted'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='PENDING', max_length=12)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('review_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='warehouse.externalmoveorder')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ExternalReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('damaged', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rejected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('movement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.stockmovement')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='warehouse.externalmoveline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='warehouse.externalreceipt')),
                ('reversal', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.stockmovement')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalStockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('RECEIVE', 'Received'), ('ISSUE', 'Issued to project'), ('PROJECT_RETURN', 'Returned from project'), ('OWNER_RETURN', 'Returned to sender'), ('REVERSE', 'Receipt reversed')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('request_key', models.UUIDField(unique=True)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='warehouse.externalmoveline')),
                ('movement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.stockmovement')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('receipt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='warehouse.externalreceipt')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='externalmoveorder',
            constraint=models.UniqueConstraint(fields=('company', 'sender_key', 'reference_key'), name='external_move_sender_reference_unique'),
        ),
        migrations.AddConstraint(
            model_name='externalmoveline',
            constraint=models.UniqueConstraint(fields=('order', 'material'), name='external_move_unique_material'),
        ),
        migrations.AddConstraint(
            model_name='externalmoveline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='external_move_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='externalmoveline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='external_move_nonnegative_cost'),
        ),
        migrations.AddConstraint(
            model_name='externalreceipt',
            constraint=models.UniqueConstraint(fields=('order', 'reference'), name='external_receipt_reference_unique'),
        ),
        migrations.AddConstraint(
            model_name='externalreceiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'order_line'), name='external_receipt_unique_line'),
        ),
        migrations.AddConstraint(
            model_name='externalreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('accepted__gte', 0), ('damaged__gte', 0), ('rejected__gte', 0)), name='external_receipt_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='externalstockevent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='external_stock_event_positive'),
        ),
    ]
