# Generated by Django 5.2.15 on 2026-08-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_supplier_compliance_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contractor_specialty',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_contractor',
            field=models.BooleanField(default=False),
        ),
    ]
