# Generated by Django 5.2.15 on 2026-08-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_supplier_contractor_specialty_supplier_is_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contractor_insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contractor_mobilisation_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contractor_rate_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contractor_safety_clearance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
