import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { api } from '@/api/services';
import { FormModal } from '@/components/common/form-modal';
import { PageToolbar } from '@/components/common/page-toolbar';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Field, inputClass } from '@/components/ui/field';
import { useToast } from '@/components/ui/toast';

export function BinLocationsPage() { const toast=useToast(); const client=useQueryClient(); const [open,setOpen]=useState(false); const bins=useQuery({queryKey:['bin-locations'],queryFn:()=>api.binLocations({page_size:100})}); const warehouses=useQuery({queryKey:['warehouses'],queryFn:()=>api.warehouses({page_size:100,is_active:true})}); const [f,setF]=useState({warehouse:'',code:'',description:''}); const save=useMutation({mutationFn:()=>api.saveBinLocation({warehouse:Number(f.warehouse),code:f.code,description:f.description,is_active:true}),onSuccess:()=>{toast.push({title:'Bin location saved',tone:'success'});void client.invalidateQueries({queryKey:['bin-locations']});setOpen(false);},onError:(e:Error)=>toast.push({title:'Could not save bin',message:e.message,tone:'danger'})}); return <div className="grid gap-4"><PageToolbar title="Bin locations" subtitle="Controlled rack, shelf, and bin locations for warehouse and project-site stores."><Button onClick={()=>setOpen(true)}><Plus className="h-4 w-4"/>Bin location</Button></PageToolbar><div className="grid gap-2">{(bins.data?.results||[]).map(b=><div key={b.id} className="flex items-center justify-between rounded-xl border border-border bg-white p-3"><div><strong>{b.code}</strong><p className="text-sm text-muted">{b.warehouse_name}{b.description?` · ${b.description}`:''}</p></div><Badge tone={b.is_active?'success':'neutral'}>{b.is_active?'Active':'Inactive'}</Badge></div>)}{!bins.data?.results.length?<p className="rounded-xl border border-dashed border-border p-4 text-sm text-muted">No bin locations configured.</p>:null}</div><FormModal open={open} title="Add bin location" onClose={()=>setOpen(false)}><form className="grid gap-3" onSubmit={(e:FormEvent)=>{e.preventDefault();save.mutate();}}><Field label="Warehouse or site store" required><select className={inputClass} value={f.warehouse} onChange={e=>setF({...f,warehouse:e.target.value})}><option value="">Select location</option>{(warehouses.data?.results||[]).map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></Field><Field label="Bin / rack code" required><input className={inputClass} value={f.code} onChange={e=>setF({...f,code:e.target.value})}/></Field><Field label="Description"><input className={inputClass} value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></Field><Button disabled={!f.warehouse||!f.code||save.isPending}>Save bin location</Button></form></FormModal></div>; }
