import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { MapPin, Pencil, Plus, Users } from 'lucide-react';
import { useState } from 'react';
import { api } from '@/api/services';
import type { ProjectSite } from '@/api/types';
import { useAuth } from '@/auth/auth-context';
import { FormModal } from '@/components/common/form-modal';
import { PageToolbar } from '@/components/common/page-toolbar';
import { Badge, statusTone } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Field, inputClass } from '@/components/ui/field';
import { useToast } from '@/components/ui/toast';

export function ProjectSitesPage() {
  const { role } = useAuth(); const toast = useToast(); const queryClient = useQueryClient();
  const [search, setSearch] = useState(''); const [project, setProject] = useState(''); const [editing, setEditing] = useState<ProjectSite | null>(null); const [creating, setCreating] = useState(false);
  const projects = useQuery({ queryKey: ['projects', 'site-directory'], queryFn: () => api.projects({ is_active: true }) });
  const sites = useQuery({ queryKey: ['project-sites', search, project], queryFn: () => api.projectSites({ search, project: project || undefined }) });
  const canManage = ['admin', 'project_manager'].includes(role || '');
  const archive = useMutation({ mutationFn: (site: ProjectSite) => api.saveProjectSite({ is_active: false, status: 'COMPLETED' }, site.id), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['project-sites'] }); toast.push({ title: 'Site archived', tone: 'success' }); }, onError: (error: Error) => toast.push({ title: 'Could not archive site', message: error.message, tone: 'danger' }) });
  const toggleClosed = useMutation({ mutationFn: (site: ProjectSite) => api.toggleProjectSiteClosed(site.id), onSuccess: (result) => { void queryClient.invalidateQueries({ queryKey: ['project-sites'] }); void queryClient.invalidateQueries({ queryKey: ['projects'] }); toast.push({ title: result.detail, tone: 'success' }); }, onError: (error: Error) => toast.push({ title: 'Could not change site closure', message: error.message, tone: 'danger' }) });
  return <div className="grid gap-4"><PageToolbar title="Project sites" subtitle="Physical construction locations. Assign people here before using the site in work orders, deliveries, or material issues." search={search} onSearch={setSearch}><select className={inputClass} value={project} onChange={(event) => setProject(event.target.value)}><option value="">All projects</option>{(projects.data?.results || []).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select>{canManage ? <Button onClick={() => setCreating(true)}><Plus className="h-4 w-4" />Add site</Button> : null}</PageToolbar><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{(sites.data?.results || []).map((site) => <Card key={site.id}><CardContent className="grid gap-3 p-4"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="font-bold">{site.name}</p><p className="text-xs text-muted">{site.project_name} · {site.code}</p></div><Badge tone={site.is_active ? statusTone(site.status) : 'neutral'}>{site.is_active ? site.status : 'Archived'}</Badge></div><p className="flex gap-2 text-sm text-muted"><MapPin className="mt-0.5 h-4 w-4 shrink-0" />{site.location || 'Location not recorded'}</p><p className="flex gap-2 text-sm"><Users className="mt-0.5 h-4 w-4 shrink-0 text-muted" />{site.manager_name || 'No site manager'}{site.engineer_names.length ? ` · ${site.engineer_names.join(', ')}` : ''}</p>{site.description ? <p className="text-sm text-muted">{site.description}</p> : null}{canManage ? <div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={() => setEditing(site)}><Pencil className="h-4 w-4" />Edit</Button>{site.is_active ? <Button size="sm" variant="ghost" onClick={() => archive.mutate(site)}>Archive</Button> : null}{site.is_active ? <Button size="sm" variant="ghost" loading={toggleClosed.isPending} onClick={() => toggleClosed.mutate(site)}>Close site</Button> : null}</div> : null}</CardContent></Card>)}{!sites.isLoading && !(sites.data?.results || []).length ? <Card><CardContent className="p-6 text-center text-sm text-muted">No project sites match this view.</CardContent></Card> : null}</div>{creating || editing ? <ProjectSiteModal site={editing} open onClose={() => { setCreating(false); setEditing(null); }} /> : null}</div>;
}

function ProjectSiteModal({ site, open, onClose }: { site: ProjectSite | null; open: boolean; onClose: () => void }) {
  const toast = useToast(); const queryClient = useQueryClient();
  const projects = useQuery({ queryKey: ['projects', 'site-form'], queryFn: () => api.projects({ is_active: true }) });
  const managers = useQuery({ queryKey: ['users', 'site-managers'], queryFn: () => api.users({ role: 'project_manager', is_active: true }) });
  const engineers = useQuery({ queryKey: ['users', 'site-engineers'], queryFn: () => api.users({ role: 'site_engineer', is_active: true }) });
  const [form, setForm] = useState({ project: String(site?.project || ''), name: site?.name || '', code: site?.code || '', location: site?.location || '', description: site?.description || '', manager: String(site?.manager || ''), site_engineers: site?.site_engineers || [], status: site?.status || 'ACTIVE', is_active: site?.is_active ?? true });
  const save = useMutation({ mutationFn: () => api.saveProjectSite({ ...form, project: Number(form.project), manager: form.manager ? Number(form.manager) : null }, site?.id), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['project-sites'] }); toast.push({ title: site ? 'Project site updated' : 'Project site created', tone: 'success' }); onClose(); }, onError: (error: Error) => toast.push({ title: 'Could not save project site', message: error.message, tone: 'danger' }) });
  const toggleEngineer = (id: number) => setForm((current) => ({ ...current, site_engineers: current.site_engineers.includes(id) ? current.site_engineers.filter((item) => item !== id) : [...current.site_engineers, id] }));
  return <FormModal open={open} title={site ? `Edit site · ${site.name}` : 'Add project site'} onClose={onClose}><form className="grid gap-3 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); save.mutate(); }}><Field label="Project" required><select className={inputClass} required value={form.project} onChange={(event) => setForm({ ...form, project: event.target.value })}><option value="">Select project</option>{(projects.data?.results || []).map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Site code" required><input className={inputClass} required value={form.code} onChange={(event) => setForm({ ...form, code: event.target.value.toUpperCase() })} placeholder="e.g. BLOCK-A" /></Field><Field label="Site name" required><input className={inputClass} required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="Location / address"><input className={inputClass} value={form.location} onChange={(event) => setForm({ ...form, location: event.target.value })} /></Field><Field label="Site manager"><select className={inputClass} value={form.manager} onChange={(event) => setForm({ ...form, manager: event.target.value })}><option value="">No site manager</option>{(managers.data?.results || []).map((user) => <option key={user.id} value={user.id}>{user.username}</option>)}</select></Field><Field label="Status"><select className={inputClass} value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="ACTIVE">Active</option><option value="ON_HOLD">On hold</option><option value="COMPLETED">Completed</option></select></Field><Field label="Site engineers" className="md:col-span-2"><div className="grid max-h-40 grid-cols-2 gap-2 overflow-auto rounded-lg border border-border p-2">{(engineers.data?.results || []).map((user) => <label key={user.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.site_engineers.includes(user.id)} onChange={() => toggleEngineer(user.id)} />{user.username}</label>)}</div></Field><Field label="Site description" className="md:col-span-2"><textarea className={inputClass} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field><Button className="md:col-span-2" disabled={save.isPending}>Save project site</Button></form></FormModal>;
}
