import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Plus, UserRoundCog } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { api } from '@/api/services';
import type { ApprovalDelegation, ProjectStaffAssignment } from '@/api/types';
import { FormModal } from '@/components/common/form-modal';
import { PageToolbar } from '@/components/common/page-toolbar';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Field, inputClass } from '@/components/ui/field';
import { useToast } from '@/components/ui/toast';

export function ProjectStaffingPage() {
  const toast = useToast(); const client = useQueryClient(); const [open, setOpen] = useState<'staff' | 'delegate' | null>(null);
  const staff = useQuery({ queryKey: ['staff-assignments'], queryFn: () => api.staffAssignments({ page_size: 100 }) });
  const delegations = useQuery({ queryKey: ['approval-delegations'], queryFn: () => api.delegations({ page_size: 100 }) });
  const deactivate = useMutation<ProjectStaffAssignment | ApprovalDelegation, Error, { kind: 'staff' | 'delegate'; id: number }>({ mutationFn: ({ kind, id }) => kind === 'staff' ? api.updateStaffAssignment(id, { is_active: false }) : api.updateDelegation(id, { is_active: false }), onSuccess: () => { toast.push({ title: 'Record deactivated', tone: 'success' }); void client.invalidateQueries({ queryKey: ['staff-assignments'] }); void client.invalidateQueries({ queryKey: ['approval-delegations'] }); }, onError: (e: Error) => toast.push({ title: 'Could not update record', message: e.message, tone: 'danger' }) });
  return <div className="grid gap-5"><PageToolbar title="Project staffing & delegation" subtitle="Manage dated project access, capacity allocations, contacts, and temporary approval coverage."><Button onClick={() => setOpen('staff')}><Plus className="h-4 w-4" />Assignment</Button><Button variant="secondary" onClick={() => setOpen('delegate')}><UserRoundCog className="h-4 w-4" />Delegate approvals</Button></PageToolbar>
  <section className="grid gap-2"><h2 className="text-base font-bold">Active and scheduled staffing</h2>{(staff.data?.results || []).map((row) => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-white p-3"><div><strong>{row.username}</strong><p className="text-sm text-muted">{row.project_name} · {row.role.replace('_', ' ')} · {row.allocation_percent}% allocation</p><p className="text-xs text-muted">{row.start_date || 'Immediate'} — {row.end_date || 'Open ended'}</p></div><div className="flex items-center gap-2"><Badge tone={row.is_active ? 'success' : 'neutral'}>{row.is_active ? 'Active' : 'Inactive'}</Badge>{row.is_active ? <Button size="sm" variant="ghost" onClick={() => deactivate.mutate({ kind: 'staff', id: row.id })}>End assignment</Button> : null}</div></div>)}{!staff.data?.results.length ? <p className="rounded-xl border border-dashed border-border p-4 text-sm text-muted">No structured staffing records yet. Existing engineer access remains visible on projects until each team member is added here.</p> : null}</section>
  <section className="grid gap-2"><h2 className="text-base font-bold">Approval delegations</h2>{(delegations.data?.results || []).map((row) => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-white p-3"><div><strong>{row.delegator_name} → {row.delegate_name}</strong><p className="text-sm text-muted">{row.project_name || 'Company-wide'} · {row.effective_from} to {row.effective_to}</p><p className="text-xs text-muted">{row.reason}</p></div>{row.is_active ? <Button size="sm" variant="ghost" onClick={() => deactivate.mutate({ kind: 'delegate', id: row.id })}>Revoke</Button> : <Badge tone="neutral">Inactive</Badge>}</div>)}</section>
  <StaffingModal mode={open} onClose={() => setOpen(null)} /></div>;
}

function StaffingModal({ mode, onClose }: { mode: 'staff' | 'delegate' | null; onClose: () => void }) {
  const toast = useToast(); const client = useQueryClient(); const projects = useQuery({ queryKey: ['projects', 'staffing'], queryFn: () => api.projects({ page_size: 100, is_active: true }) }); const users = useQuery({ queryKey: ['users', 'staffing'], queryFn: () => api.users({ page_size: 100, is_active: true }) }); const [f, setF] = useState({ project: '', user: '', role: 'ENGINEER', allocation: '100', from: '', to: '', reason: '' }); const set = (k: keyof typeof f, v: string) => setF((x) => ({ ...x, [k]: v }));
  const m = useMutation<ProjectStaffAssignment | ApprovalDelegation>({ mutationFn: () => mode === 'staff' ? api.createStaffAssignment({ project: Number(f.project), user: Number(f.user), role: f.role, allocation_percent: f.allocation, start_date: f.from || null, end_date: f.to || null, is_active: true }) : api.createDelegation({ delegate: Number(f.user), project: f.project ? Number(f.project) : null, effective_from: f.from, effective_to: f.to, reason: f.reason, is_active: true }), onSuccess: () => { toast.push({ title: mode === 'staff' ? 'Staff assignment saved' : 'Approval delegation saved', tone: 'success' }); void client.invalidateQueries({ queryKey: ['staff-assignments'] }); void client.invalidateQueries({ queryKey: ['approval-delegations'] }); onClose(); }, onError: (e: Error) => toast.push({ title: 'Could not save', message: e.message, tone: 'danger' }) });
  return <FormModal open={!!mode} title={mode === 'staff' ? 'Add project staffing' : 'Delegate approval cover'} onClose={onClose}><form className="grid gap-3 md:grid-cols-2" onSubmit={(e: FormEvent) => { e.preventDefault(); m.mutate(); }}><Field label="Project" required={mode === 'staff'}><select className={inputClass} value={f.project} onChange={(e) => set('project', e.target.value)}><option value="">{mode === 'delegate' ? 'All projects' : 'Select project'}</option>{(projects.data?.results || []).map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label={mode === 'staff' ? 'Team member' : 'Delegate'} required><select className={inputClass} value={f.user} onChange={(e) => set('user', e.target.value)}><option value="">Select user</option>{(users.data?.results || []).map((u) => <option key={u.id} value={u.id}>{u.username} — {u.role_display}</option>)}</select></Field>{mode === 'staff' ? <><Field label="Project role"><select className={inputClass} value={f.role} onChange={(e) => set('role', e.target.value)}><option value="ENGINEER">Site engineer</option><option value="MANAGER">Project manager</option><option value="SITE_CONTACT">Site contact</option></select></Field><Field label="Allocation %"><input className={inputClass} type="number" min="0" max="100" value={f.allocation} onChange={(e) => set('allocation', e.target.value)} /></Field></> : <Field label="Reason" required className="md:col-span-2"><textarea className={inputClass} value={f.reason} onChange={(e) => set('reason', e.target.value)} /></Field>}<Field label="Effective from" required={mode === 'delegate'}><input className={inputClass} type="date" value={f.from} onChange={(e) => set('from', e.target.value)} /></Field><Field label="Effective to" required={mode === 'delegate'}><input className={inputClass} type="date" value={f.to} onChange={(e) => set('to', e.target.value)} /></Field><Button className="md:col-span-2" disabled={!f.user || (mode === 'staff' && !f.project) || (mode === 'delegate' && (!f.from || !f.to || !f.reason)) || m.isPending}>Save</Button></form></FormModal>;
}
