import { useQuery } from '@tanstack/react-query';
import { ArrowLeft, Box, CheckCircle2, FileText, PackageCheck, Truck } from 'lucide-react';
import type { ReactNode } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { api } from '@/modules/procurement/api';
import type { GoodsReceivedNote } from '@/modules/procurement/types';
import type { RecordActivity } from '@/api/types';
import { useAuth } from '@/auth/auth-context';
import { Badge, statusTone } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { formatDate, formatNumber, formatUGX } from '@/lib/utils';
import './purchase-order-detail.css';

function Card({ title, children }: { title: string; children: ReactNode }) { return <section className="po-detail-card"><header><h2>{title}</h2></header>{children}</section>; }
function Meta({ label, value }: { label: string; value: ReactNode }) { return <div className="po-detail-meta"><span>{label}</span><strong>{value || '—'}</strong></div>; }
function receivedByItem(notes: GoodsReceivedNote[]) { const received = new Map<number, number>(); const rejected = new Map<number, number>(); notes.forEach((note) => note.items.forEach((item) => { received.set(item.purchase_order_item, (received.get(item.purchase_order_item) || 0) + Number(item.accepted_quantity)); rejected.set(item.purchase_order_item, (rejected.get(item.purchase_order_item) || 0) + Number(item.rejected_quantity) + Number(item.damaged_quantity)); })); return { received, rejected }; }
function Workflow({ progress }: { progress: number }) { const steps = ['Approved', 'Issued', 'Dispatched', 'In transit', 'Arrived', 'Received', 'Closed']; return <ol className="po-detail-steps">{steps.map((step, index) => { const complete = progress >= ((index + 1) / steps.length) * 100; return <li key={step} className={complete ? 'complete' : ''}><span>{complete ? <CheckCircle2 size={14} /> : index + 1}</span><small>{step}</small></li>; })}</ol>; }
function Activity({ events }: { events: RecordActivity[] }) { return events.length ? <ol className="po-detail-activity">{events.slice(0, 6).map((event) => <li key={event.id}><CheckCircle2 size={15} /><div><strong>{event.action.replaceAll('_', ' ')}</strong><small>{event.actor} · {formatDate(event.created_at)}</small>{event.message ? <p>{event.message}</p> : null}</div></li>)}</ol> : <p className="po-detail-muted">No activity has been recorded yet.</p>; }

export function PurchaseOrderDetailPage() {
  const { orderId = '' } = useParams(); const id = Number(orderId); const navigate = useNavigate(); const { user, role } = useAuth();
  const order = useQuery({ queryKey: ['purchase-order-detail', id], queryFn: () => api.purchaseOrder(id), enabled: Number.isFinite(id) && id > 0 });
  const activity = useQuery({ queryKey: ['purchase-order-activity', id], queryFn: () => api.purchaseOrderActivity(id), enabled: !!order.data });
  const sourceRequest = useQuery({ queryKey: ['purchase-order-source-request', order.data?.purchase_request], queryFn: () => api.purchaseRequest(order.data!.purchase_request!), enabled: !!order.data?.purchase_request });
  const receipts = useQuery({ queryKey: ['purchase-order-receipts', id], queryFn: () => api.goodsReceivedNotes({ purchase_order: id, page_size: 50 }), enabled: !!order.data });
  if (order.isLoading) return <main className="po-detail-page"><p className="po-detail-loading">Loading purchase order…</p></main>;
  if (order.isError || !order.data) return <main className="po-detail-page"><Card title="Purchase order unavailable"><p className="po-detail-muted">This record may have been removed or you may not have permission to view it.</p><Button asChild><Link to="/procurement/purchase-orders">Return to purchase orders</Link></Button></Card></main>;
  const record = order.data; const receiptRows = receipts.data?.results || []; const quantities = receivedByItem(receiptRows); const orderedQuantity = record.items.reduce((sum, item) => sum + Number(item.quantity || 0), 0); const acceptedQuantity = receiptRows.flatMap((receipt) => receipt.items).reduce((sum, item) => sum + Number(item.accepted_quantity || 0), 0); const progress = orderedQuantity ? Math.min(100, Math.round((acceptedQuantity / orderedQuantity) * 100)) : 0; const nextAction = record.status === 'PENDING' ? 'Send the priced purchase order to Finance for budget review.' : record.status === 'ORDERED' ? 'Confirm supplier dispatch or follow up delivery.' : record.status === 'PARTIAL' ? 'Record the remaining receipt.' : record.status === 'RECEIVED' ? 'Receipt complete; Finance can match the supplier invoice.' : 'Monitor the order progress and evidence.';
  return <main className="po-detail-page">
    <div className="po-detail-breadcrumb"><Button variant="ghost" aria-label="Back to purchase orders" onClick={() => navigate(-1)}><ArrowLeft size={16} />Purchase orders</Button><span>Procurement / Purchase orders / {record.number}</span></div>
    <section className="po-detail-hero"><div><p>PROCUREMENT / PURCHASE ORDERS</p><h1>{record.number}</h1><span>{record.supplier_name || 'Supplier to be confirmed'} · {record.project_name || 'No project'}</span></div><div className="po-detail-status"><Badge tone={statusTone(record.status)}>{record.status_display}</Badge><Badge tone={record.delivery_destination === 'SITE' ? 'info' : 'success'}>{record.delivery_destination_display}</Badge></div><div className="po-detail-actions">{record.status === 'PENDING' && record.purchase_request && ['finance_officer', 'finance_manager', 'admin'].includes(role || '') ? <Button asChild><Link to={`/procurement/requests?search=${encodeURIComponent(record.purchase_request_number || '')}`}>Open finance review</Link></Button> : null}<Button variant="secondary" asChild><Link to={`/procurement/requests/${record.purchase_request}/`}>View source PR</Link></Button><details><summary aria-label="More purchase order actions">⋮</summary><div><Link to="/procurement/purchase-orders">Open register</Link></div></details></div></section>
    <section className="po-detail-meta-row"><Meta label="Supplier" value={record.supplier_name || 'To be confirmed'} /><Meta label="Project / site" value={record.project_name || 'No project'} /><Meta label="PO date" value={formatDate(record.created_at)} /><Meta label="Expected delivery" value={record.expected_delivery_date ? formatDate(record.expected_delivery_date) : 'Not set'} /><Meta label="Destination" value={record.delivery_destination_display} /></section>
    <div className="po-detail-layout"><div className="po-detail-main">
      <Card title="Order summary"><div className="po-detail-summary"><div><span>Order value</span><strong>{formatUGX(record.total_cost)}</strong></div><div><span>Delivery route</span><strong>{record.delivery_destination_display}</strong></div><div><span>Receipt progress</span><strong>{progress}%</strong></div></div><div className="po-detail-primary"><div><strong>Next action</strong><p>{nextAction}</p></div><Link to="/procurement/deliveries">Open delivery register</Link></div></Card>
      <Card title="Ordered materials"><div className="po-detail-table-wrap"><table><thead><tr><th>Material</th><th>Specification</th><th>Ordered</th><th>Unit price</th><th>Line total</th><th>Received</th><th>Outstanding</th><th>Status</th></tr></thead><tbody>{record.items.map((item) => { const accepted = quantities.received.get(item.id) || 0; const rejected = quantities.rejected.get(item.id) || 0; const outstanding = Math.max(0, Number(item.quantity) - accepted); return <tr key={item.id}><td><strong>{item.material_name}</strong><small>{item.material_code || 'Material'}</small></td><td>{item.notes || 'No specification'}</td><td>{formatNumber(item.quantity)} {item.unit}</td><td>{formatUGX(item.unit_price)}</td><td>{formatUGX(item.line_total)}</td><td>{formatNumber(accepted)}<small>{rejected ? `${formatNumber(rejected)} rejected/damaged` : 'Accepted'}</small></td><td>{formatNumber(outstanding)} {item.unit}</td><td><Badge tone={outstanding === 0 ? 'success' : accepted > 0 ? 'warning' : 'info'}>{outstanding === 0 ? 'Received' : accepted > 0 ? 'Part received' : 'Awaiting receipt'}</Badge></td></tr>; })}</tbody><tfoot><tr><td colSpan={4}>Final total</td><td>{formatUGX(record.total_cost)}</td><td colSpan={3} /></tr></tfoot></table></div></Card>
      <Card title="Delivery and receiving"><div className="po-detail-progress"><div><span><b style={{ width: `${progress}%` }} /></span><small>{progress}% receipt completion</small></div><Badge tone={progress === 100 ? 'success' : 'warning'}>{progress === 100 ? 'Received' : 'In progress'}</Badge></div><Workflow progress={progress} /><div className="po-detail-fields"><Meta label="Dispatch confirmed" value={record.dispatch_confirmed_at ? formatDate(record.dispatch_confirmed_at) : 'Not confirmed'} /><Meta label="Received by" value={record.received_by_username || 'Awaiting receipt'} /><Meta label="Actual receipt" value={record.received_at ? formatDate(record.received_at) : 'Not received'} /><Meta label="Delivery revision" value={record.delivery_revision_reason || 'None'} /></div></Card>
      <Card title="Source and purpose"><p className="po-detail-source">{record.purchase_request ? <Link to={`/procurement/requests/${record.purchase_request}/`}>{record.purchase_request_number}</Link> : 'No linked purchase request'} · source purchase request</p><p className="po-detail-text">{sourceRequest.data?.justification || record.notes || 'No purpose or procurement notes recorded.'}</p></Card>
    </div><aside className="po-detail-side">
      <Card title="Approval and finance"><div className="po-detail-side-list"><Meta label="Approval status" value={record.status_display} /><Meta label="Finance review" value={record.finance_status_display || (user?.soft_finance_enabled ? 'Ready for handoff' : 'Not enabled')} /><Meta label="Order value" value={formatUGX(record.total_cost)} /></div>{record.status === 'PENDING' && record.purchase_request ? <Button variant="secondary" asChild><Link to={`/procurement/requests?search=${encodeURIComponent(record.purchase_request_number || '')}`}>View finance decision</Link></Button> : null}{user?.soft_finance_enabled ? <p className="po-detail-info">Invoices reduce the commitment; posted payments settle the liability without duplicating expenditure.</p> : null}</Card>
      <Card title="Related records"><div className="po-detail-links"><Link to={`/procurement/requests/${record.purchase_request}/`}><FileText size={16} />Source purchase request</Link><Link to="/procurement/deliveries"><Truck size={16} />Deliveries</Link><Link to="/procurement/grns"><PackageCheck size={16} />Goods received notes <b>{receiptRows.length}</b></Link><Link to="/inventory/movements"><Box size={16} />Stock movements</Link></div></Card>
      <Card title="Activity and audit"><Activity events={activity.data || []} /></Card>
    </aside></div>
  </main>;
}
