import { CheckCircle2, ClipboardPlus, FileText, Play, Plus, ShieldCheck, TrendingUp } from 'lucide-react';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useParams } from 'react-router-dom';
import { api } from '@/api/services';
import { qk } from '@/api/queryKeys';
import type { WorkOrder } from '@/api/types';
import { useAuth } from '@/auth/auth-context';
import { FormModal } from '@/components/common/form-modal';
import { ExportButton } from '@/components/common/export-button';
import { PageToolbar } from '@/components/common/page-toolbar';
import { Badge, statusTone } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Field, inputClass } from '@/components/ui/field';
import { SearchableSelect } from '@/components/ui/searchable-select';
import { useToast } from '@/components/ui/toast';
import { WorkOrderOperations } from '@/components/work-orders/work-order-operations';
import { WorkspaceTabs } from '@/components/common/workspace-hub';

const labels: Record<string, string> = { submit: 'Submit', approve: 'Technical approve', assign: 'Assign', 'accept-assignment': 'Accept contractor assignment', start: 'Start work', complete: 'Mark complete', verify: 'Verify', close: 'Close', reject: 'Reject', hold: 'Put on hold', cancel: 'Cancel' };

export function WorkOrdersPage() {
  const { workOrderId } = useParams(); const { role, user } = useAuth(); const queryClient = useQueryClient();
  const [status, setStatus] = useState('ACTIVE'); const [creating, setCreating] = useState(false); const [selected, setSelected] = useState<WorkOrder | null>(null); const [pendingAction, setPendingAction] = useState<{ order: WorkOrder; action: string } | null>(null);
  const orders = useQuery({ queryKey: ['work-orders', status], queryFn: () => api.workOrders(status === 'ACTIVE' || status === 'ALL' ? {} : { status }) });
  const metrics = useQuery({ queryKey: qk.workOrderMetrics, queryFn: api.workOrderMetrics });
  const actionQueue = useQuery({ queryKey: qk.workOrderActionQueue, queryFn: api.workOrderActionQueue });
  const selectedDetail = useQuery({ queryKey: ['work-order', workOrderId], queryFn: () => api.workOrder(Number(workOrderId)), enabled: Boolean(workOrderId) });
  const selectedOrder = workOrderId ? selectedDetail.data || (orders.data?.results || []).find((order) => order.id === Number(workOrderId)) || null : selected;
  const canWrite = ['admin', 'project_manager', 'site_engineer'].includes(role || '');
  const refresh = () => { void queryClient.refetchQueries({ queryKey: ['work-orders'], type: 'all' }); void queryClient.refetchQueries({ queryKey: ['work-order', workOrderId], type: 'all' }); void queryClient.refetchQueries({ queryKey: qk.workOrderMetrics, type: 'all' }); void queryClient.refetchQueries({ queryKey: qk.workOrderActionQueue, type: 'all' }); };
  const visibleOrders = (orders.data?.results || []).filter((order) => status !== 'ACTIVE' || !['CLOSED', 'REJECTED', 'CANCELLED'].includes(order.status));
  return <div className="grid gap-3 sm:gap-4">
    <WorkspaceTabs links={[{ href: '/work-orders', label: 'Work orders', description: 'Create and manage work', icon: ClipboardPlus }, { href: '/work-orders/progress', label: 'Site progress', description: 'Track execution', icon: TrendingUp }, { href: '/work-orders/invoices', label: 'Invoices', description: 'Review billings', icon: FileText }]} />
    <PageToolbar title="Work orders" subtitle="Scope, budget, assignment, execution, site close-out, and financial traceability in one controlled record."><select className={inputClass} value={status} onChange={(e) => setStatus(e.target.value)}><option value="ACTIVE">Active work (default)</option><option value="ALL">All statuses</option>{['DRAFT','SUBMITTED','APPROVED','ASSIGNED','IN_PROGRESS','COMPLETED','VERIFIED','CLOSED','REJECTED','ON_HOLD','CANCELLED'].map((item) => <option key={item}>{item}</option>)}</select><ExportButton label="Excel" onClick={() => void api.downloadWorkOrders('xlsx', status !== 'ACTIVE' && status !== 'ALL' ? { status } : {})} /><ExportButton label="PDF" onClick={() => void api.downloadWorkOrders('pdf', status !== 'ACTIVE' && status !== 'ALL' ? { status } : {})} />{canWrite ? <Button onClick={() => setCreating(true)}><Plus className="h-4 w-4" />New work order</Button> : null}</PageToolbar>
    <div className="grid grid-cols-2 gap-2 lg:grid-cols-4">{[['Open', metrics.data?.open], ['In progress', metrics.data?.in_progress], ['Overdue', metrics.data?.overdue], ['Completed', metrics.data?.completed]].map(([label, value]) => <Card key={String(label)}><CardContent className="p-3 sm:p-3.5"><p className="text-[10px] font-bold uppercase tracking-wide text-muted">{label}</p><p className="mt-1 text-xl font-black">{value ?? '–'}</p></CardContent></Card>)}</div>
    {(actionQueue.data?.requires_action || []).length ? <Card className="border-warning/30"><CardContent className="p-3"><p className="text-[10px] font-black uppercase tracking-[0.14em] text-warning">Action required</p><p className="mt-0.5 text-sm font-bold">Work orders assigned to your role</p><div className="mt-2 grid gap-2">{actionQueue.data!.requires_action.slice(0, 5).map((order) => <button key={order.id} className="flex items-center justify-between gap-2 rounded-xl border border-warning/20 bg-warning/5 p-2.5 text-left text-sm hover:bg-warning/10" onClick={() => setSelected(order)}><span className="min-w-0 truncate"><strong>{order.number}</strong> · {order.title}</span><Badge tone={statusTone(order.status)}>{order.status_display}</Badge></button>)}</div></CardContent></Card> : null}
    {orders.isError ? <Card><CardContent className="p-4 text-sm text-critical">Work orders could not be loaded. Refresh the page or try again.</CardContent></Card> : null}
    <div className="grid gap-2">{visibleOrders.map((order) => <Card key={order.id} className={selectedOrder?.id === order.id ? 'ring-2 ring-info/30' : ''}><CardContent className="grid gap-2 p-3 sm:grid-cols-[1fr_auto] sm:p-4"><button className="min-w-0 text-left" onClick={() => setSelected(order)}><div className="flex flex-wrap items-center gap-2"><strong>{order.number} · {order.title}</strong><Badge tone={statusTone(order.status)}>{order.status_display}</Badge>{order.is_overdue ? <Badge tone="danger">Overdue</Badge> : null}{order.finance_reviewed_at ? <Badge tone="success">Budget reviewed</Badge> : null}</div><p className="mt-1 text-sm text-muted">{order.project_name} · {order.site_name || `${order.site_packages.length} site package${order.site_packages.length === 1 ? '' : 's'}`} · {order.priority_display} priority · Scope v{order.scope_version}</p><p className="mt-1 text-sm">Owner: {order.responsible_person_name || order.contractor_name || 'Unassigned'} · Due: {order.revised_due_date || order.due_date || 'Not set'}</p><p className="mt-1 text-xs text-muted">Planned {Number(order.estimated_cost).toLocaleString()} · Actual {Number(order.actual_cost).toLocaleString()} · {order.tasks.filter((task) => task.status !== 'COMPLETED').length} open task{order.tasks.filter((task) => task.status !== 'COMPLETED').length === 1 ? '' : 's'}</p></button><div className="flex flex-wrap gap-2">{actionsFor(order, role, user?.id).map((action) => <Button key={action} size="sm" variant={action === 'approve' || action === 'verify' ? 'default' : 'secondary'} onClick={() => setPendingAction({ order, action })}>{action === 'approve' || action === 'verify' ? <ShieldCheck className="h-4 w-4" /> : action === 'start' ? <Play className="h-4 w-4" /> : <CheckCircle2 className="h-4 w-4" />}{labels[action]}</Button>)}{['admin', 'finance_manager'].includes(role || '') && order.status === 'APPROVED' && !order.finance_reviewed_at && Number(order.estimated_cost) > 0 ? <Button size="sm" variant="secondary" onClick={() => setSelected(order)}>Review budget</Button> : null}</div></CardContent></Card>)}{!orders.isLoading && !orders.isError && !visibleOrders.length ? <Card><CardContent className="p-6 text-center text-sm text-muted">No work orders match this view. Complete or change the filter to see closed work.</CardContent></Card> : null}</div>
    <WorkOrderModal open={creating} onClose={() => setCreating(false)} />
    {selectedOrder ? <WorkOrderOperations order={selectedOrder} onClose={() => setSelected(null)} /> : null}
    {pendingAction ? <WorkOrderActionModal pending={pendingAction} onClose={() => setPendingAction(null)} onDone={() => { refresh(); setPendingAction(null); }} /> : null}
  </div>;
}

function actionsFor(order: WorkOrder, role: string | null, userId?: number) {
  const manager = ['admin','project_manager'].includes(role || ''); const writer = manager || role === 'site_engineer';
  if (order.status === 'DRAFT') return writer ? ['submit'] : [];
  if (order.status === 'SUBMITTED') return manager ? ['approve','reject','hold'] : [];
  if (order.status === 'APPROVED') return manager ? ['assign','hold'] : [];
  if (order.status === 'ASSIGNED') {
    if (order.assignment_status === 'PENDING') {
      const assignedInternal = Boolean(userId && (order.responsible_person === userId || order.responsible_team.includes(userId)));
      const contractorOnly = Boolean(order.contractor && !order.responsible_person && !order.responsible_team.length);
      if (assignedInternal || (contractorOnly && manager)) return ['accept-assignment', 'hold'];
      return manager ? ['hold'] : [];
    }
    return writer ? ['start','hold'] : [];
  }
  if (order.status === 'IN_PROGRESS') return writer ? ['complete','hold'] : [];
  if (order.status === 'COMPLETED') return manager ? ['verify'] : [];
  if (order.status === 'VERIFIED') return manager ? ['close'] : [];
  return [];
}

function WorkOrderActionModal({ pending, onClose, onDone }: { pending: { order: WorkOrder; action: string }; onClose: () => void; onDone: () => void }) {
  const { order, action } = pending; const toast = useToast(); const users = useQuery({ queryKey: ['users', 'work-order-assignment'], queryFn: () => api.users({ is_active: true, page_size: 100 }) }); const suppliers = useQuery({ queryKey: ['suppliers', 'work-order-assignment'], queryFn: () => api.suppliers({ is_active: true, page_size: 100 }) });
  const [form, setForm] = useState({ responsible_person: '', contractor: '', comments: '', hold_owner: '', hold_recovery_date: '' }); const assigning = action === 'assign'; const holding = action === 'hold'; const needsReason = ['reject', 'hold', 'cancel'].includes(action);
  const submit = useMutation({ mutationFn: () => assigning ? api.assignWorkOrder(order.id, { responsible_person: form.responsible_person ? Number(form.responsible_person) : null, contractor: form.contractor ? Number(form.contractor) : null, notes: form.comments }) : action === 'accept-assignment' ? api.acceptWorkOrderAssignment(order.id) : api.workOrderTransition(order.id, action, form.comments, holding ? { hold_owner: Number(form.hold_owner), hold_recovery_date: form.hold_recovery_date } : {}), onSuccess: () => { toast.push({ title: `${labels[action]} completed`, tone: 'success' }); onDone(); }, onError: (error: Error) => toast.push({ title: 'Action could not be completed', message: error.message, tone: 'danger' }) });
  const contractors = (suppliers.data?.results || []).filter((supplier: any) => supplier.is_contractor); const staff = (users.data?.results || []) as any[];
  return <FormModal open title={`${labels[action]} · ${order.number}`} onClose={onClose}><form className="grid gap-3" onSubmit={(event) => { event.preventDefault(); submit.mutate(); }}>{assigning ? <><Field label="Responsible employee"><SearchableSelect value={form.responsible_person} onChange={(responsible_person) => setForm({ ...form, responsible_person })} options={staff.map((person) => ({ value: person.id, label: person.full_name || person.first_name || person.username }))} placeholder="Search employees" /></Field><Field label="Contractor"><SearchableSelect value={form.contractor} onChange={(contractor) => setForm({ ...form, contractor })} options={contractors.map((supplier: any) => ({ value: supplier.id, label: supplier.name }))} placeholder="Search contractors" /></Field></> : null}{holding ? <><Field label="Hold owner" required><SearchableSelect required value={form.hold_owner} onChange={(hold_owner) => setForm({ ...form, hold_owner })} options={staff.map((person) => ({ value: person.id, label: person.full_name || person.username }))} placeholder="Search follow-up owners" /></Field><Field label="Recovery date" required><input className={inputClass} required type="date" value={form.hold_recovery_date} onChange={(event) => setForm({ ...form, hold_recovery_date: event.target.value })} /></Field></> : null}<Field label={needsReason ? 'Reason' : 'Notes'} required={needsReason}><textarea className={inputClass} required={needsReason} value={form.comments} onChange={(event) => setForm({ ...form, comments: event.target.value })} /></Field><Button disabled={submit.isPending}>{labels[action]}</Button></form></FormModal>;
}

function WorkOrderModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { data: projects } = useQuery({ queryKey: ['projects', 'work-order'], queryFn: () => api.projects({ is_active: true }) }); const toast = useToast(); const qc = useQueryClient(); const [form, setForm] = useState({ project: '', title: '', description: '', work_category: '', priority: 'NORMAL', estimated_start_date: '', due_date: '', estimated_cost: '0', notes: '', is_emergency: false, emergency_reason: '', emergency_spend_cap: '0' });
  const save = useMutation({ mutationFn: () => api.saveWorkOrder({ ...form, project: Number(form.project), estimated_start_date: form.estimated_start_date || null, due_date: form.due_date || null, estimated_cost: form.estimated_cost }), onSuccess: () => { void qc.invalidateQueries({ queryKey: ['work-orders'] }); toast.push({ title: 'Work order created', tone: 'success' }); onClose(); }, onError: (e: Error) => toast.push({ title: 'Could not create work order', message: e.message, tone: 'danger' }) });
  return <FormModal open={open} title="New work order" onClose={onClose}><form className="grid gap-3 sm:grid-cols-2" onSubmit={(e) => { e.preventDefault(); save.mutate(); }}><Field label="Lead project" required><select className={inputClass} required value={form.project} onChange={(e) => setForm({ ...form, project: e.target.value })}><option value="">Select project</option>{(projects?.results || []).map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Priority"><select className={inputClass} value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}>{['LOW','NORMAL','HIGH','URGENT'].map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Title" required className="sm:col-span-2"><input className={inputClass} required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></Field><Field label="Description" required className="sm:col-span-2"><textarea className={inputClass} required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field><Field label="Work category"><input className={inputClass} value={form.work_category} onChange={(e) => setForm({ ...form, work_category: e.target.value })} /></Field><Field label="Estimated cost"><input className={inputClass} type="number" min="0" value={form.estimated_cost} onChange={(e) => setForm({ ...form, estimated_cost: e.target.value })} /></Field><Field label="Estimated start"><input className={inputClass} type="date" value={form.estimated_start_date} onChange={(e) => setForm({ ...form, estimated_start_date: e.target.value })} /></Field><Field label="Due date"><input className={inputClass} type="date" value={form.due_date} onChange={(e) => setForm({ ...form, due_date: e.target.value })} /></Field><Field label="Emergency work" className="sm:col-span-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_emergency} onChange={(e) => setForm({ ...form, is_emergency: e.target.checked })} />Use only for service restoration or safety incidents.</label></Field>{form.is_emergency ? <><Field label="Emergency reason" required><textarea className={inputClass} required value={form.emergency_reason} onChange={(e) => setForm({ ...form, emergency_reason: e.target.value })} /></Field><Field label="Emergency spend cap"><input className={inputClass} type="number" min="0" value={form.emergency_spend_cap} onChange={(e) => setForm({ ...form, emergency_spend_cap: e.target.value })} /></Field></> : null}<Button className="sm:col-span-2" disabled={save.isPending}><ClipboardPlus className="h-4 w-4" />Create master draft</Button></form></FormModal>;
}
