import type { ColumnDef } from '@tanstack/react-table';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { LockKeyhole, Plus, UnlockKeyhole, Upload } from 'lucide-react';
import { FormEvent, useState } from 'react';
import { financeApi } from '@/modules/finance/api';
import type { Account, FiscalPeriod, Journal } from '@/modules/finance/types';
import { qk } from '@/api/queryKeys';
import { can } from '@/api/roles';
import { useAuth } from '@/auth/auth-context';
import { FormModal } from '@/components/common/form-modal';
import { Pagination } from '@/components/common/pagination';
import { Button } from '@/components/ui/button';
import { DataTable } from '@/components/ui/data-table';
import { Field, inputClass } from '@/components/ui/field';
import { useToast } from '@/components/ui/toast';
import { useListState } from '@/hooks/use-list-state';
import { cn, formatDate, formatMoney } from '@/lib/utils';
import { FinancePage, Status } from './components';

type Tab = 'journals' | 'accounts' | 'periods';

export function FinanceLedgerPage() {
  const { role } = useAuth(); const [tab, setTab] = useState<Tab>('journals'); const [creating, setCreating] = useState(false); const list = useListState({ status: '', account_type: '' }); const client = useQueryClient(); const toast = useToast();
  const journals = useQuery({ queryKey: qk.financeJournals(list.query), queryFn: () => financeApi.journals(list.query), enabled: tab === 'journals' }); const accounts = useQuery({ queryKey: qk.financeAccounts(list.query), queryFn: () => financeApi.accounts(list.query), enabled: tab === 'accounts' }); const periods = useQuery({ queryKey: ['finance', 'periods', list.query], queryFn: () => financeApi.fiscalPeriods(list.query), enabled: tab === 'periods' });
  const refresh = () => Promise.all([
    client.invalidateQueries({ queryKey: ['finance'] }),
    client.invalidateQueries({ queryKey: qk.workflowBadges }),
  ]);
  const journalCommand = useMutation({ mutationFn: ({ id, action, body }: { id: number; action: string; body?: unknown }) => financeApi.journalCommand(id, action, body), onSuccess: async () => { toast.push({ title: 'Journal posted successfully', tone: 'success' }); await refresh(); }, onError: (error: Error) => toast.push({ title: 'Journal posting failed', message: error.message, tone: 'danger' }) });
  const periodCommand = useMutation({ mutationFn: ({ id, action }: { id: number; action: 'open' | 'close' }) => financeApi.periodCommand(id, action), onSuccess: async (_, variables) => { toast.push({ title: `Fiscal period ${variables.action}ed`, tone: 'success' }); await refresh(); }, onError: (error: Error) => toast.push({ title: 'Period action failed', message: error.message, tone: 'danger' }) });
  const journalColumns: ColumnDef<Journal>[] = [{ header: 'Journal', cell: ({ row }) => <div><strong>{row.original.number}</strong><p className="mt-0.5 text-xs text-foreground">{row.original.description}</p><p className="text-xs text-muted">{row.original.source_type} / {row.original.source_reference || 'manual'}</p></div> }, { header: 'Status', cell: ({ row }) => <Status value={row.original.status} /> }, { header: 'Date', cell: ({ row }) => formatDate(row.original.date) }, { header: 'Debit', cell: ({ row }) => formatMoney(row.original.debit_total ?? row.original.lines.reduce((sum, line) => sum + Number(line.debit), 0)) }, { header: 'Credit', cell: ({ row }) => formatMoney(row.original.credit_total ?? row.original.lines.reduce((sum, line) => sum + Number(line.credit), 0)) }, { id: 'actions', header: '', cell: ({ row }) => can.manageFinance(role) && row.original.status === 'DRAFT' ? <div className="flex justify-end"><Button size="sm" loading={journalCommand.isPending && journalCommand.variables?.id === row.original.id} loadingLabel="Posting" onClick={() => journalCommand.mutate({ id: row.original.id, action: 'post' })}><Upload className="h-3.5 w-3.5" />Post</Button></div> : null }];
  const accountColumns: ColumnDef<Account>[] = [{ header: 'Account', cell: ({ row }) => <div><strong>{row.original.code}</strong><p className="mt-0.5 text-xs text-foreground">{row.original.name}</p></div> }, { header: 'Type', cell: ({ row }) => <Status value={row.original.account_type} /> }, { header: 'System mapping', cell: ({ row }) => row.original.system_key || '-' }, { header: 'Manual posting', cell: ({ row }) => row.original.allow_manual_posting ? 'Allowed' : 'System only' }, { header: 'Status', cell: ({ row }) => <Status value={row.original.is_active ? 'ACTIVE' : 'INACTIVE'} /> }];
  const periodColumns: ColumnDef<FiscalPeriod>[] = [{ header: 'Period', cell: ({ row }) => <strong>{row.original.name}</strong> }, { header: 'Status', cell: ({ row }) => <Status value={row.original.status} /> }, { header: 'Start', cell: ({ row }) => formatDate(row.original.start_date) }, { header: 'End', cell: ({ row }) => formatDate(row.original.end_date) }, { id: 'actions', header: '', cell: ({ row }) => can.manageFinance(role) ? <div className="flex justify-end"><Button size="sm" variant="secondary" loading={periodCommand.isPending && periodCommand.variables?.id === row.original.id} loadingLabel={row.original.status === 'OPEN' ? 'Closing' : 'Reopening'} onClick={() => periodCommand.mutate({ id: row.original.id, action: row.original.status === 'OPEN' ? 'close' : 'open' })}>{row.original.status === 'OPEN' ? <LockKeyhole className="h-3.5 w-3.5" /> : <UnlockKeyhole className="h-3.5 w-3.5" />}{row.original.status === 'OPEN' ? 'Close' : 'Reopen'}</Button></div> : null }];
  return <FinancePage eyebrow="Financial accounting" title="General ledger" description="Review the chart of accounts, control fiscal periods, and post balanced journals through governed actions." actions={can.prepareFinance(role) && tab === 'journals' ? <Button onClick={() => setCreating(true)}><Plus className="h-4 w-4" />Manual journal</Button> : undefined}>
    <div className="grid gap-2 border border-border bg-white p-2.5 shadow-panel sm:p-3"><div className="flex overflow-x-auto border border-border">{([['journals','Journals'],['accounts','Chart of accounts'],['periods','Fiscal periods']] as const).map(([value,label]) => <button key={value} className={cn('shrink-0 border-r border-border px-3 py-2 text-xs font-bold last:border-0', tab === value ? 'bg-primary text-white' : 'bg-white text-muted')} onClick={() => { setTab(value); list.setPage(1); }}>{label}</button>)}</div><div className="grid gap-2 sm:flex sm:flex-wrap"><input className={inputClass} value={list.search} onChange={(event) => list.setSearch(event.target.value)} placeholder={`Search ${tab.replace('-', ' ')}`} /><select className={inputClass} value={list.filters.status} onChange={(event) => list.setFilter('status', event.target.value)}><option value="">All statuses</option><option>DRAFT</option><option>POSTED</option><option>REVERSED</option><option>OPEN</option><option>CLOSED</option></select></div></div>
    {tab === 'journals' ? <><DataTable columns={journalColumns} mobileSummaryCells={2} data={journals.data?.results || []} emptyTitle={journals.isLoading ? 'Loading journals...' : 'No journals found'} /><Pagination page={list.page} setPage={list.setPage} data={journals.data} /></> : null}{tab === 'accounts' ? <><DataTable columns={accountColumns} mobileSummaryCells={2} data={accounts.data?.results || []} emptyTitle={accounts.isLoading ? 'Loading accounts...' : 'No accounts found'} /><Pagination page={list.page} setPage={list.setPage} data={accounts.data} /></> : null}{tab === 'periods' ? <><DataTable columns={periodColumns} mobileSummaryCells={2} data={periods.data?.results || []} emptyTitle={periods.isLoading ? 'Loading periods...' : 'No fiscal periods found'} /><Pagination page={list.page} setPage={list.setPage} data={periods.data} /></> : null}
    <JournalModal open={creating} onClose={() => setCreating(false)} />
  </FinancePage>;
}

function JournalModal({ open, onClose }: { open: boolean; onClose: () => void }) { const accounts = useQuery({ queryKey: qk.financeAccounts({ page_size: 200 }), queryFn: () => financeApi.accounts({ page_size: 200, is_active: true }) }); const eligible = accounts.data?.results.filter((item) => item.allow_manual_posting) || []; const [form, setForm] = useState({ date: new Date().toISOString().slice(0,10), description: '', source_reference: '', debit_account: '', credit_account: '', amount: '', line_description: '' }); const toast = useToast(); const client = useQueryClient(); const mutation = useMutation({ mutationFn: () => financeApi.createJournal({ client_uuid: crypto.randomUUID(), date: form.date, description: form.description, source_reference: form.source_reference, lines: [{ account: Number(form.debit_account), description: form.line_description || form.description, debit: form.amount, credit: '0' }, { account: Number(form.credit_account), description: form.line_description || form.description, debit: '0', credit: form.amount }] }), onSuccess: () => { toast.push({ title: 'Balanced journal draft created', tone: 'success' }); void client.invalidateQueries({ queryKey: ['finance'] }); onClose(); }, onError: (error: Error) => toast.push({ title: 'Could not create journal', message: error.message, tone: 'danger' }) }); return <FormModal open={open} title="Prepare manual journal" onClose={onClose}><form className="grid gap-3" onSubmit={(event: FormEvent) => { event.preventDefault(); mutation.mutate(); }}><div className="grid gap-3 md:grid-cols-2"><Field label="Journal date" required><input className={inputClass} type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></Field><Field label="Source reference"><input className={inputClass} value={form.source_reference} onChange={(event) => setForm({ ...form, source_reference: event.target.value })} /></Field></div><Field label="Description" required><input className={inputClass} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field><div className="grid gap-3 border border-border p-3 md:grid-cols-3"><AccountSelect label="Debit account" value={form.debit_account} set={(value) => setForm({ ...form, debit_account: value })} accounts={eligible} /><AccountSelect label="Credit account" value={form.credit_account} set={(value) => setForm({ ...form, credit_account: value })} accounts={eligible} /><Field label="Amount" required><input className={inputClass} type="number" min="0.01" step="0.01" value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} /></Field></div><Button loading={mutation.isPending} loadingLabel="Creating draft" disabled={!form.description || !form.debit_account || !form.credit_account || form.debit_account === form.credit_account || !form.amount}>Create balanced draft</Button></form></FormModal>; }
function AccountSelect({ label, value, set, accounts }: { label: string; value: string; set: (value: string) => void; accounts: Account[] }) { return <Field label={label} required><select className={inputClass} value={value} onChange={(event) => set(event.target.value)}><option value="">Select account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.code} / {account.name}</option>)}</select></Field>; }
