import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, Plus, Send, Upload, X } from 'lucide-react';
import { FormEvent, useMemo, useState } from 'react';
import { financeApi } from '@/modules/finance/api';
import { qk } from '@/api/queryKeys';
import type { PaymentBatch } from '@/modules/finance/types';
import { useAuth } from '@/auth/auth-context';
import { FormModal } from '@/components/common/form-modal';
import { ExportButton } from '@/components/common/export-button';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Field, inputClass } from '@/components/ui/field';
import { useToast } from '@/components/ui/toast';
import { formatDate, formatMoney } from '@/lib/utils';
import { FinancePage, Status } from './components';

export function FinancePaymentBatchesPage() {
  const { role } = useAuth(); const canPrepare = ['finance_officer', 'finance_manager', 'admin'].includes(role || ''); const canManage = ['finance_manager', 'admin'].includes(role || '');
  const [create, setCreate] = useState(false); const [reason, setReason] = useState<PaymentBatch | null>(null); const toast = useToast(); const client = useQueryClient();
  const batches = useQuery({ queryKey: qk.financePaymentBatches({ page_size: 100 }), queryFn: () => financeApi.paymentBatches({ page_size: 100 }) });
  const refresh = () => client.invalidateQueries({ queryKey: qk.finance });
  const action = useMutation({ mutationFn: ({ id, name, body }: { id: number; name: 'submit' | 'approve' | 'release' | 'cancel'; body?: unknown }) => financeApi.paymentBatchCommand(id, name, body), onSuccess: async (_, value) => { toast.push({ title: `Batch ${value.name}ted`, tone: 'success' }); await refresh(); setReason(null); }, onError: (error: Error) => toast.push({ title: 'Batch action failed', message: error.message, tone: 'danger' }) });
  return <FinancePage eyebrow="Payment control" title="Payment batches" description="Group compatible approved vouchers, obtain a separate release approval, then post the entire payment run atomically." actions={canPrepare ? <Button onClick={() => setCreate(true)}><Plus className="h-4 w-4" />New batch</Button> : undefined}>
      <div className="grid gap-2">{batches.isLoading ? <Card><CardContent className="p-4 text-sm text-muted">Loading payment batches…</CardContent></Card> : null}{!batches.isLoading && !batches.data?.results.length ? <Card><CardContent className="p-4 text-sm text-muted">No payment batches have been prepared.</CardContent></Card> : null}{batches.data?.results.map((batch) => <Card key={batch.id}><CardContent className="grid gap-2 p-3 sm:grid-cols-[1fr_auto]"><div><div className="flex flex-wrap gap-2"><strong>{batch.number}</strong><Status value={batch.status} /></div><p className="mt-1 text-sm">{batch.source_account_name} · {batch.currency_code} · {formatDate(batch.payment_date)}</p><p className="mt-1 text-xs text-muted">{batch.items.length} payment{batch.items.length === 1 ? '' : 's'} · {batch.items.map((item) => item.payment_number).join(', ')}</p>{batch.notes ? <p className="mt-1 text-xs text-muted">{batch.notes}</p> : null}{batch.cancellation_reason ? <p className="mt-1 text-xs text-critical">Cancelled: {batch.cancellation_reason}</p> : null}</div><div className="flex flex-wrap items-center gap-2 sm:justify-end"><strong>{formatMoney(batch.total_amount, batch.currency_code)}</strong><ExportButton label="PDF" onClick={() => void financeApi.downloadPaymentBatch(batch.id, 'pdf', batch.number)} /><ExportButton label="Excel" onClick={() => void financeApi.downloadPaymentBatch(batch.id, 'xlsx', batch.number)} />{canPrepare && batch.status === 'DRAFT' ? <Button size="sm" loading={action.isPending} onClick={() => action.mutate({ id: batch.id, name: 'submit' })}><Send className="h-3.5 w-3.5" />Submit</Button> : null}{canManage && batch.status === 'SUBMITTED' ? <Button size="sm" loading={action.isPending} onClick={() => action.mutate({ id: batch.id, name: 'approve' })}><Check className="h-3.5 w-3.5" />Approve</Button> : null}{canManage && batch.status === 'APPROVED' ? <Button size="sm" loading={action.isPending} onClick={() => action.mutate({ id: batch.id, name: 'release' })}><Upload className="h-3.5 w-3.5" />Release & post</Button> : null}{canManage && ['DRAFT','SUBMITTED','APPROVED'].includes(batch.status) ? <Button size="sm" variant="ghost" onClick={() => setReason(batch)}><X className="h-3.5 w-3.5" />Cancel</Button> : null}</div></CardContent></Card>)}</div>
    <BatchModal open={create} onClose={() => setCreate(false)} />
    <CancelModal batch={reason} onClose={() => setReason(null)} onConfirm={(reasonText) => reason && action.mutate({ id: reason.id, name: 'cancel', body: { reason: reasonText } })} pending={action.isPending} />
  </FinancePage>;
}

function BatchModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const payments = useQuery({ queryKey: qk.financePayments({ page_size: 100, status: 'APPROVED' }), queryFn: () => financeApi.payments({ page_size: 100, status: 'APPROVED' }), enabled: open }); const toast = useToast(); const client = useQueryClient();
  const [selected, setSelected] = useState<number[]>([]); const [notes, setNotes] = useState('');
  const choices = useMemo(() => payments.data?.results || [], [payments.data?.results]); const first = choices.find((payment) => selected.includes(payment.id));
  const compatible = useMemo(() => !first ? choices : choices.filter((payment) => payment.source_account === first.source_account && payment.currency === first.currency), [choices, first]);
  const mutation = useMutation({ mutationFn: () => { if (!first) throw new Error('Select at least one approved payment.'); return financeApi.createPaymentBatch({ source_account: first.source_account, currency: first.currency, payment_date: new Date().toISOString().slice(0, 10), payment_ids: selected, notes }); }, onSuccess: async () => { toast.push({ title: 'Payment batch created', tone: 'success' }); await client.invalidateQueries({ queryKey: qk.finance }); onClose(); }, onError: (error: Error) => toast.push({ title: 'Could not create batch', message: error.message, tone: 'danger' }) });
  const toggle = (id: number) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  return <FormModal open={open} title="Prepare payment batch" onClose={onClose}><form className="grid gap-3" onSubmit={(event: FormEvent) => { event.preventDefault(); mutation.mutate(); }}><p className="text-sm text-muted">Choose approved payments from one cash account and currency. The batch must be approved by someone other than its preparer before release.</p><div className="grid max-h-72 gap-2 overflow-auto border border-border p-2">{compatible.map((payment) => <label key={payment.id} className="flex cursor-pointer items-center justify-between gap-2 border-b border-border py-2 text-sm"><span><input className="mr-2" type="checkbox" checked={selected.includes(payment.id)} onChange={() => toggle(payment.id)} />{payment.number} / {payment.supplier_name}</span><strong>{formatMoney(payment.amount, payment.currency_code)}</strong></label>)}{!compatible.length ? <p className="text-sm text-muted">No approved payment vouchers are ready for batching.</p> : null}</div><Field label="Run note"><input className={inputClass} value={notes} onChange={(event) => setNotes(event.target.value)} /></Field><Button loading={mutation.isPending} disabled={!selected.length}>Create batch</Button></form></FormModal>;
}

function CancelModal({ batch, onClose, onConfirm, pending }: { batch: PaymentBatch | null; onClose: () => void; onConfirm: (reason: string) => void; pending: boolean }) { const [text, setText] = useState(''); return <FormModal open={!!batch} title={`Cancel ${batch?.number || 'batch'}`} onClose={onClose}><form className="grid gap-3" onSubmit={(event) => { event.preventDefault(); onConfirm(text); }}><Field label="Reason" required><textarea className={inputClass} rows={3} value={text} onChange={(event) => setText(event.target.value)} /></Field><Button variant="warning" loading={pending} disabled={!text}>Cancel batch</Button></form></FormModal>; }
