# Generated by Django 5.2.15 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('notifications', '0003_webpushsubscription')]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                max_length=30,
                choices=[
                    ('low_stock', 'Low stock'), ('pr_submitted', 'PR submitted'),
                    ('pr_approved', 'PR approved'), ('pr_rejected', 'PR rejected'),
                    ('po_created', 'PO created'), ('po_received', 'PO received'),
                    ('supplier_claim_opened', 'Supplier claim opened'), ('system', 'System'),
                    ('budget_approval_required', 'Budget approval required'),
                    ('budget_threshold_reached', 'Budget threshold reached'),
                    ('po_exceeding_budget', 'PO exceeding budget'),
                    ('invoice_submitted', 'Invoice submitted'),
                    ('invoice_match_exception', 'Invoice matching exception'),
                    ('invoice_due_soon', 'Invoice due soon'), ('invoice_overdue', 'Invoice overdue'),
                    ('payment_awaiting_approval', 'Payment awaiting approval'),
                    ('payment_approved', 'Payment approved'), ('payment_rejected', 'Payment rejected'),
                    ('staff_advance_overdue', 'Staff advance overdue'),
                    ('valuation_adjustment', 'Valuation adjustment'),
                    ('journal_posting_failure', 'Journal posting failure'),
                ],
            ),
        ),
    ]
