# Generated by Django 5.2.15 on 2026-09-18 06:12

from django.db import migrations, models


def update_material_request_copy(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    for notification in Notification.objects.filter(notification_type__startswith='pr_').iterator():
        title = notification.title.replace('Purchase request', 'Material request').replace('purchase request', 'material request').replace('PR ', 'MR ').replace('PR-', 'MR-')
        message = notification.message.replace('Purchase request', 'Material request').replace('purchase request', 'material request').replace('PR ', 'MR ').replace('PR-', 'MR-')
        Notification.objects.filter(pk=notification.pk).update(title=title, message=message)


def restore_purchase_request_copy(apps, schema_editor):
    Notification = apps.get_model('notifications', 'Notification')
    for notification in Notification.objects.filter(notification_type__startswith='pr_').iterator():
        title = notification.title.replace('Material request', 'Purchase request').replace('material request', 'purchase request').replace('MR ', 'PR ').replace('MR-', 'PR-')
        message = notification.message.replace('Material request', 'Purchase request').replace('material request', 'purchase request').replace('MR ', 'PR ').replace('MR-', 'PR-')
        Notification.objects.filter(pk=notification.pk).update(title=title, message=message)


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_emailnotificationpreference_emaildelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'Low stock'), ('pr_submitted', 'MR submitted'), ('pr_approved', 'MR approved'), ('pr_rejected', 'MR rejected'), ('po_created', 'PO created'), ('po_received', 'PO received'), ('supplier_claim_opened', 'Supplier claim opened'), ('system', 'System'), ('budget_approval_required', 'Budget approval required'), ('budget_threshold_reached', 'Budget threshold reached'), ('po_exceeding_budget', 'PO exceeding budget'), ('invoice_submitted', 'Invoice submitted'), ('invoice_match_exception', 'Invoice matching exception'), ('invoice_due_soon', 'Invoice due soon'), ('invoice_overdue', 'Invoice overdue'), ('payment_awaiting_approval', 'Payment awaiting approval'), ('payment_approved', 'Payment approved'), ('payment_rejected', 'Payment rejected'), ('staff_advance_overdue', 'Staff advance overdue'), ('valuation_adjustment', 'Valuation adjustment'), ('journal_posting_failure', 'Journal posting failure')], max_length=30),
        ),
        migrations.RunPython(update_material_request_copy, restore_purchase_request_copy),
    ]
